### ISSUE TITLE
Add "tabbed" output modes

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#1]
The current display of a bunch of content separated by `hr`s is... less than optimal. I'm thinking something like 

![image](https://cloud.githubusercontent.com/assets/174509/16420766/d3ce46c4-3d0f-11e6-9d8b-3a4ef86dfbd1.png)

**Comment by echochamber** [comment]
I think it should look exactly like that, right down to the painted lines!

**Comment by shepmaster** [comment]
Closed via #14
