### ISSUE TITLE
Allow selecting the other Ace keybindings and themes

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#10]
Loading these async would probably be ideal, but I'm not sure how to do that, yet...

**Comment by cuviper** [comment]
Vim bindings are a big point for me.  I feel crippled in plain text input...

**Comment by syakhmi** [comment]
You might consider embedding a more full-featured editor, like Ace: https://ace.c9.io/build/kitchen-sink.html

**Comment by syakhmi** [comment]
Nvm, I see Ace is already used :)

**Comment by moosingin3space** [comment]
What about using [Monaco](https://github.com/Microsoft/moncao-editor)?

**Comment by shepmaster** [comment]
@moosingin3space your link appears invalid. Could you provide a list of benefits that Monaco would provide over Ace?

**Comment by moosingin3space** [comment]
@shepmaster fixed the link.

**Comment by steveklabnik** [comment]
:+1: for vim :heart:

**Comment by shepmaster** [comment]
Closed via #40 and #44.
