### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by dtolnay** [integer32llc/rust-playground#103]
I can't run a simple `fn main() {}` on any of the channels:

> Sandbox operation failed: Unable to execute the compiler: Out of memory (os error 12)

**Comment by shepmaster** [comment]
Yep. Currently, I pay for the Playground out of pocket, which means I'm on the lowest EC2 tier. 1GiB of RAM and .... evidently I forgot to re-enable the swap. Perhaps that's what is causing it. It's happening right now because it's building the containers for the next hour or so.

**Comment by shepmaster** [comment]
You'll be pleased to know that crates like syntex and serde always seem to be the Big Ones when it comes to compile time and memory usage 😈

**Comment by shepmaster** [comment]
Ok, I've added the swap to `/etc/fstab`, so I'm going to close this for now. Thank you for poking me to see what the problem was ;-)
