### ISSUE TITLE
build.sh installs stale nightly from 2017-02-13

### ISSUE THREAD

**Issue by dwrensha** [integer32llc/rust-playground#110]
When I follow the installation instructions in the README, I get this error as clippy is being built:

```
   Compiling clippy_lints v0.0.116

error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 1 field
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.116/src/utils/mod.rs:903:9
    |
903 |         Def::Macro(id, _) => Some(id),
    |         ^^^^^^^^^^^^^^^^^ expected 1 field, found 2

...

Caused by:
  Could not compile `clippy_lints`.
```

The problem is that `curl https://static.rust-lang.org/dist/channel-rust-nightly-date.txt`, as invoked [here](https://github.com/integer32llc/rust-playground/blob/ca075b4f9598ebd3057f6ce759b57fc70ab175fa/compiler/build.sh#L16), returns "2017-02-13", so we end up an outdated nightly rustc that can no longer compile clippy.

This seems to have to do with the [new release infrastructure](https://internals.rust-lang.org/t/rust-release-infrastructure-changes-and-rls-packaging/4626). As far as I can tell, nowadays the best way to get the latest nightly release date is to do `curl https://static.rust-lang.org/dist/channel-rust-nightly.toml` and then to parse the TOML result. Unfortunately, adding such logic to build.sh does not appear to be a trivial change. :(

Perhaps it would be worthwhile to ask the people in charge of the release infrastructure if they could continue to support the `current-rust-nightly-date.txt` thing.

**Comment by shepmaster** [comment]
@alexcrichton, could I trouble you to ask if no longer updating `/dist/channel-rust-nightly-date.txt` and friends is deliberate? If it is deliberate and deprecated, is `dist/channel-rust-nightly.toml` the correct replacement?

**Comment by alexcrichton** [comment]
@shepmaster I wouldn't say it's either deliberate or not deliberate :)

I'd recommend using the TOML format for now, but if you'd like to continue using `channel-rust-nightly-date.txt` I believe it'll just require updating the [manifest construction step](https://github.com/rust-lang/rust/blob/master/src/tools/build-manifest/src/main.rs) in the build system.

**Comment by shepmaster** [comment]
@alexcrichton 

> using the TOML format **for now**

(emphasis mine) That wording makes it sounds like you expect that the `-date.txt` file will receive updates again in the future; am I reading you correctly?

If I'm the only person that uses that file, I certainly don't want to add any maintenance burden to the build system; I can write some shell to pull out the date from the TOML file easily enough.

If you think other people are also relying on that file, I'd be happy to submit a PR that adds it back.

**Comment by alexcrichton** [comment]
Oh I probably won't personally have a chance to send a PR any time soon, but if you'd like to do so then the maintenance should be super small so I'd be more than happy to r+!
