### ISSUE TITLE
Add button to copy permalink to clipboard

### ISSUE THREAD

**Issue by matklad** [integer32llc/rust-playground#117]
Feature request, feel free to ignore :) 

It would be convenient for me if clicking on the **Gist** button copied the url to the playground to the clipboard. This is what I actually want most of the time, and at the moment I have to find the actual link in the other part of the page and right click it.

**Comment by shepmaster** [comment]
I agree that this is my most common usecase as well. I'll have to dig a bit, as I'm not 100% that the browser will let you do this — things like this often have to happen in *direct* reaction to a user click, but saving to a Gist has a network transaction and a callback.

While I'm playing with that, do you have any ideas on how the availability of this could be communicated? Having it copy automatically would be nice for the 2 people that know it happens, but having other people be able to make use of it would be good too.

Additionally, I wonder if there's any issue of clobbering the user's clipboard if they *don't* know this will automatically replace it...

**Comment by matklad** [comment]
>While I'm playing with that, do you have any ideas on how the availability of this could be communicated? 

If it turns out to be impossible to fill the clipboard asynchronously, it should be possible to place "Copy to clipboard" link alongside the "Permalink to the playground" link.

If it **is** possible, then the good UI would be to split the "Gist" button into two parts and add a clipboard icon to the right part. 

Also github's UI for cloning repositories presents copy nicely:

![screenshot_2017-03-19_21-14-46](https://cloud.githubusercontent.com/assets/1711539/24083514/2754475e-0ce9-11e7-8eee-5bc92df6e675.png)

**Comment by matklad** [comment]
>While I'm playing with that, do you have any ideas on how the availability of this could be communicated? 

Hey, what if clicking on `Share` button changed the URL from `https://play.rust-lang.org` to `?gist=567a4c13c0b2d35cca59a65831c06008&version=stable`? (Is it even possible to change URL in this way without reloading the page?) Then, to copy one would need only `Ctrl+L` + `Ctrl+C`.

**Comment by shepmaster** [comment]
I'm going to add the "copy to clipboard" button; feel free to open a followup issue for changing the URL after creating a gist.
