### ISSUE TITLE
Editor text clips into format style selection list

### ISSUE THREAD

**Issue by Cldfire** [integer32llc/rust-playground#129]
I noticed this while updating my playground theme to reflect the recent changes to the HTML.

Screenshot:

![spectacle lh8652](https://cloud.githubusercontent.com/assets/13814214/24574602/5b66fefa-1663-11e7-92f5-bcbce7250095.png)

**Comment by shepmaster** [comment]
Thank you very much! For my own curiosity, would you mind sharing what your overall theme looks like? I'm always looking for sources of inspiration!

**Comment by Cldfire** [comment]
Sure :)

The editor (I override the chrome theme):


![screenshot_20170401_102824](https://cloud.githubusercontent.com/assets/13814214/24579568/f7577cf6-16c5-11e7-8f70-a2a62cef5816.png)


The help page (just cleaned this up last night):


![screenshot_20170401_102441](https://cloud.githubusercontent.com/assets/13814214/24579551/cdc9dd7a-16c5-11e7-9e23-60c87e01f5e7.png)


The repo is [here](https://github.com/Cldfire/ayu-rs) if you want to look at it in any detail. Be warned, the CSS is pretty bad; I'm not an expert.
