### ISSUE TITLE
Re-enable RUST_BACKTRACE

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#132]
Is the old implementation faster again? Does it need to be opt-in from the end user?

**Comment by xftroxgpx** [comment]
[example](https://play.rust-lang.org/?gist=6d9b0fcad212068a11abb68d4e457fb5&version=nightly) workaround:
```rust
use std::env;

fn main() {
    env::set_var("RUST_BACKTRACE", "1");

    let one_plus_one = stringify!(1 + a);
    assert_eq!(one_plus_one, "1 + 1");
}
```

**Comment by durka** [comment]
Workaround isn't enough for compiler ICEs. Why not just bring back the URL query param?

**Comment by RalfJung** [comment]
Ideally, there'd also be a way to discover that param somewhere. Like, detect if the output suggests to turn on RUST_BACKTRACE, then add a link somewhere which has the param set.

**Comment by xftroxgpx** [comment]
Would something _like_ this make sense? for setting env var(s):

```rust
// env: RUST_BACKTRACE=1
// env: SOMETHINGELSE=whatever whenever assuming data until end of line
// //env: CC=/usr/bin/cc
// ^ commented out env aka not in effect
fn main() {
    let one_plus_one = stringify!(1 + a);
    assert_eq!(one_plus_one, "1 + 1");
}
```

Assuming they were parsed from the above and set _before_ running the compiler.
Or could that be a potential security issue? if use could set any env var.
Or is it too complicated/messy to want it implemented?

**Comment by xftroxgpx** [comment]
Example ICE that I just stumbled upon([but was already found by others](https://github.com/rust-lang/rust/issues/43197)), re durka's [comment](https://github.com/integer32llc/rust-playground/issues/132#issuecomment-317895791):

```rust
pub const X: i64 = std::i64::MAX + 1;
fn main() {
    println!("{}", X);
}
```
([^ playground link](https://play.rust-lang.org/?gist=bcef2b956253bbd4ed6afd21ea6714a0&version=nightly))

<details>
 <summary>
output
</summary>
<div style="white-space: pre-wrap;">
<pre style="white-space: pre-wrap;">
<div style="white-space: pre-wrap;">
   Compiling playground v0.0.1 (file:///playground)
warning: constant evaluation error: attempt to add with overflow. This will become a HARD ERROR in the future
 --> src/main.rs:1:20
  |
1 | pub const X: i64 = std::i64::MAX + 1;
  |                    ^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(const_err)] on by default

error[E0080]: constant evaluation error
 --> src/main.rs:1:20
  |
1 | pub const X: i64 = std::i64::MAX + 1;
  |                    ^^^^^^^^^^^^^^^^^ attempt to add with overflow

error: internal compiler error: /checkout/src/librustc_trans/mir/constant.rs:396: _1 not initialized
 --> src/main.rs:3:20
  |
3 |     println!("{}", X);
  |                    ^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (52a330969 2017-07-27) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
</div>
</pre>
If someone knows how to make github wrap long lines in the above output, please let me know. 
</div>
</details>

------

[playground link](https://gist.github.com/eaae31f2fca316b87823bff06441fee8) for this ICE with [durka's workaround](https://github.com/integer32llc/rust-playground/issues/132#issuecomment-317895791) for displaying ICE stacktraces - thank you btw!
<details>
<summary>
code for the above
</summary>
<pre>
use std::io::Write;
use std::fs::File;
use std::process::Command;

fn main() {
    let code = stringify!(
        pub const X: i64 = std::i64::MAX + 1;
fn main() {
    println!("{}", X);
}

    );

    writeln!(File::create("foo.rs").unwrap(), "{}", code).unwrap();

    let cmd = Command::new("rustc")
        .env("RUST_BACKTRACE", "full")
        .arg("+nightly")
        .arg("foo.rs")
        .status()
        .unwrap();
    println!("exit code {}", cmd);
}

</pre>
</details>
<details>

<summary>
output for the above
</summary>
<pre>
   Compiling playground v0.0.1 (file:///playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.86 secs
     Running `target/debug/playground`
warning: constant evaluation error: attempt to add with overflow. This will become a HARD ERROR in the future
 --> foo.rs:1:21
  |
1 | pub const X : i64 = std :: i64 :: MAX + 1 ; fn main (  ) {
  |                     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(const_err)] on by default

error[E0080]: constant evaluation error
 --> foo.rs:1:21
  |
1 | pub const X : i64 = std :: i64 :: MAX + 1 ; fn main (  ) {
  |                     ^^^^^^^^^^^^^^^^^^^^^ attempt to add with overflow

error: internal compiler error: /checkout/src/librustc_trans/mir/constant.rs:396: _1 not initialized
 --> foo.rs:2:20
  |
2 | println ! ( "{}" , X ) ; }
  |                    ^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (52a330969 2017-07-27) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8
stack backtrace:
   0:     0x7f0cbc947db3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h1e2c58aa3ff6d86d
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f0cbc942494 - std::sys_common::backtrace::_print::h021c974b848276a0
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x7f0cbc955c33 - std::panicking::default_hook::{{closure}}::heee72575d0ec5077
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:380
   3:     0x7f0cbc955928 - std::panicking::default_hook::hfd71e7dd65b0a86c
                               at /checkout/src/libstd/panicking.rs:390
   4:     0x7f0cbc956137 - std::panicking::rust_panic_with_hook::h4eba8d7e50a7fffa
                               at /checkout/src/libstd/panicking.rs:610
   5:     0x7f0cbb84f878 - std::panicking::begin_panic::h48e4cf472e4fad07
   6:     0x7f0cbb87b668 - rustc::session::opt_span_bug_fmt::{{closure}}::haf7ee303771aa9d5
   7:     0x7f0cbb87b4c7 - rustc::session::span_bug_fmt::haa62c77dec292770
   8:     0x7f0cbb91a0f3 - rustc_trans::mir::constant::MirConstContext::const_lvalue::h1dbacf146fcd1592
   9:     0x7f0cbb91aeec - rustc_trans::mir::constant::MirConstContext::const_rvalue::h1269edfb1e998250
  10:     0x7f0cbb91898c - rustc_trans::mir::constant::MirConstContext::trans::hfa9f803bd5275c21
  11:     0x7f0cbb91e7bf - rustc_trans::mir::constant::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_constant::h5da8b49ad7fff201
  12:     0x7f0cbb921fa1 - rustc_trans::mir::operand::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_operand::hec9f10a4034bfc20
  13:     0x7f0cbb923684 - rustc_trans::mir::rvalue::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_rvalue_operand::h865cdcdd7c0b92cf
  14:     0x7f0cbb90c713 - rustc_trans::mir::trans_mir::h559e0cace6be4e5a
  15:     0x7f0cbb92ff33 - rustc_trans::trans_item::TransItem::define::h8e122b431d2e3ba3
  16:     0x7f0cbb8d4bed - rustc_trans::base::trans_crate::module_translation::hc4a2a7b27dcd9f96
  17:     0x7f0cbb8cecfe - rustc_trans::base::trans_crate::h15091f3336a483e1
  18:     0x7f0cbcd02902 - rustc_driver::driver::phase_4_translate_to_llvm::h911c0cc67ac5141c
  19:     0x7f0cbcccf79a - rustc_driver::driver::compile_input::{{closure}}::h81c7e0ebddde0b7a
  20:     0x7f0cbcd0174e - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::hea490b5adce91e62
  21:     0x7f0cbcce3823 - rustc_driver::driver::phase_3_run_analysis_passes::h1210be0da5a54c32
  22:     0x7f0cbcccdb30 - rustc_driver::driver::compile_input::hbf08f2b62431a302
  23:     0x7f0cbcd12f65 - rustc_driver::run_compiler::h7b5ef3de0e76a53e
  24:     0x7f0cbcc2c477 - std::sys_common::backtrace::__rust_begin_short_backtrace::he953d71f28957e91
  25:     0x7f0cbc98567c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  26:     0x7f0cbcc63e60 - <F as alloc::boxed::FnBox<A>>::call_box::hb0c50b1ae5590427
  27:     0x7f0cbc954b2b - std::sys::imp::thread::Thread::new::thread_start::h8cc7df731d74d00c
                               at /checkout/src/liballoc/boxed.rs:692
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  28:     0x7f0cb7aec6b9 - start_thread
  29:     0x7f0cbc6023dc - clone
  30:                0x0 - <unknown>

Standard Output
exit code exit code: 101
</pre>
</details>

**Comment by shepmaster** [comment]
As a datapoint, with Rust 1.19, it takes 2.48 seconds to compile and execute "hello world" with `RUST_BACKTRACE` set; it takes 1.64 without. That's almost a whole second more; 150% of the time without. I don't think that it's reasonable yet to have this on by default. 

<summary>
<details>

```rust
fn main() {
    println!("Hello, world!");
}
```

WITH:

2.65
1.91
2.56
2.37
2.68
2.60
2.45
2.57
2.53
2.43

WITHOUT

1.69
1.66
1.67
1.63
1.58
1.55
1.52
1.66
1.67
1.74
</details>
</summary>

**Comment by durka** [comment]
That's crazy! What changes when the env var is turned on, besides the
output at the end when it crashes?

Anyway, URL parameter is lookin' pretty good...

**Comment by shepmaster** [comment]
> What changes when the env var is turned on, besides the
> output at the end when it crashes?

I don't fully know. It's much better than the [10-20 seconds that used to be added](https://github.com/rust-lang/rust/issues/37477).

An intermediate solution (that would likely require some rearchitecting in the sandbox) would be to split the beautiful `cargo run` command into `cargo build` and then `cargo run` (or run the program directly?). It's my hope that it's the fact it's set during *compilation* that causes the problem.

Having the backtrace on user code makes for a much nicer user experience; I'm not that worried about making ICEs easier to debug by default; that could live as a config option.

**Comment by shepmaster** [comment]
I edited my previous comment, but the short version:

| `RUST_BACKTRACE`    | time (seconds) |
|---------------------|----------------|
| compile and execute |           2.48 |
| execute             |           2.02 |
| disabled            |           1.64 |

**Comment by shepmaster** [comment]
<summary>

For `rustc 1.20.0-nightly (15aa15b03 2017-07-21)`:

| `RUST_BACKTRACE`    | time (seconds) |
|---------------------|----------------|
| compile and execute |           4.19 |
| execute             |           3.31 |
| disabled            |           2.99 |

<details>

**execute**

3.35
3.21
3.28
3.08
3.37
3.41
3.09
3.25
3.58
3.44

**compile and execute**

3.88
4.22
4.35
3.95
4.07
3.83
4.35
4.30
4.51
4.43

**disabled**

2.76
2.81
2.89
3.16
2.98
3.08
3.03
2.99
3.08
3.07
</details>
</summary>

**Comment by shepmaster** [comment]
More numbers from directly inside the Docker container:

<summary>

|                                                               | time (seconds) |
|---------------------------------------------------------------|----------------|
| `RUST_BACKTRACE=1 cargo run`                                  |          1.159 |
| `env RUST_BACKTRACE=1 cargo build; ./target/debug/playground` |          1.214 |
| `cargo build; env RUST_BACKTRACE=1 ./target/debug/playground` |          0.676 |
| `RUST_BACKTRACE=1 cargo run`                                  |          0.672 |

<details>

for i in $(seq 10); do touch src/main.rs && time env RUST_BACKTRACE=1 cargo run; done

1.132
1.161
1.124
1.140
1.129
1.157
1.146
1.201
1.212
1.184

for i in $(seq 10); do touch src/main.rs && time bash -c 'env RUST_BACKTRACE=1 cargo build; ./target/debug/playground'; done

1.199
1.212
1.165
1.199
1.242
1.201
1.234
1.233
1.231
1.223

for i in $(seq 10); do touch src/main.rs && time bash -c 'cargo build; env RUST_BACKTRACE=1 ./target/debug/playground'; done

0.657
0.652
0.671
0.675
0.656
0.668
0.659
0.661
0.761
0.695

for i in $(seq 10); do touch src/main.rs && time env cargo run; done

0.661
0.637
0.655
0.644
0.649
0.674
0.663
0.708
0.716
0.714

```
 rustc -vV
rustc 1.19.0 (0ade33941 2017-07-17)
binary: rustc
commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
commit-date: 2017-07-17
host: x86_64-unknown-linux-gnu
release: 1.19.0
LLVM version: 4.0
```

</details>
</summary>
