### ISSUE TITLE
Formatting "invalid" code does not show an error

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#156]
Try to format this:

```rust
let a = {
    1
};
```

Since it's not in a function, rustfmt returns the following stderr:

```
error: expected item, found `let`
 --> /playground/src/main.rs:1:1
  |
1 | let a = {
  | ^^^
```

But we don't show it anywhere.

**Comment by aravind-pg** [comment]
Is this easy to fix by any chance? I've definitely been stumped by this shortcoming at times.

**Comment by shepmaster** [comment]
> Is this easy to fix by any chance?

I'm not entirely sure because I've not really dug into it 😈 

Here's a rough sketch of what I'd do:

1. Find the action that is called in case of failure: https://github.com/integer32llc/rust-playground/blob/6ba7b0f9541c9dea50b5c8b4b7cdb318e8e6a4c2/ui/frontend/actions.ts#L470-L472

1. Check to see [where that action is reduced](https://github.com/integer32llc/rust-playground/blob/6ba7b0f9541c9dea50b5c8b4b7cdb318e8e6a4c2/ui/frontend/reducers/output/format.ts)

1. Check [other reducers to see how they manage state in such cases](https://github.com/integer32llc/rust-playground/blob/6ba7b0f9541c9dea50b5c8b4b7cdb318e8e6a4c2/ui/frontend/reducers/output/execute.ts)

1. Check to see [how the output is displayed](https://github.com/integer32llc/rust-playground/blob/6ba7b0f9541c9dea50b5c8b4b7cdb318e8e6a4c2/ui/frontend/Output.tsx)

In general, I think so long as the UI only displays something extra on formatting failure and that's cleared when you start a new format, then that would be a big step in the right direction. Sometimes it just involves playing with the UI to get the flow right 😉

**Comment by aravind-pg** [comment]
Interesting, appreciate the directions! Will try to find a little time for this this weekend or so.
