### ISSUE TITLE
Please disable or change Ctrl-L / Command-L ("go to line") keyboard shortcut

### ISSUE THREAD

**Issue by mbrubeck** [integer32llc/rust-playground#160]
This conflicts with the "focus location bar" shortcut in most web browsers, and doesn't work in at all in some of those browsers. See also rust-lang/rust-playpen#293.

**Comment by est31** [comment]
Could be changed to Ctrl-G

**Comment by shepmaster** [comment]
Probably something like https://stackoverflow.com/questions/17633324/ace-editor-change-ctrlh-keybinding

**Comment by mbrubeck** [comment]
The rust-lang/ playpen code uses [this technique](https://github.com/rust-lang/rust-playpen/blob/6759d8d4be2a61d33e866e133e4b13eb316bef6f/static/web.js#L780-L785), though it feels a bit fragile.

**Comment by shepmaster** [comment]
@mbrubeck :-( As an Emacs and macOS user, <kbd>control</kbd>-<kbd>t</kbd> not transposing would make me real sad. However, That's only for the emacs mode, which you have to opt-into at least.

**Comment by shepmaster** [comment]
But the technique is appreciated ^_^

**Comment by xftroxgpx** [comment]
I was always using `Alt+D`, had no idea `Ctrl+L` also works. Thanks!
