### ISSUE TITLE
Use the crates from the libz blitz?

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#168]
These aren't just arbitrary crates, but are of high-quality. Who should we talk to about this?

**Comment by budziq** [comment]
Hi as discussed on [users.rust-lang.org](https://users.rust-lang.org/t/the-official-rust-playground-now-has-the-top-100-crates-available/11817/18)

In the context of regard to [rust-cookbook](https://github.com/brson/rust-cookbook/issues/87) we would be interested in rest/js consumable list of crates supported on the playground at any given time (We would like to know which examples in cookbook are would be runable in the playground)

Also we would be awesome if we could somehow coordinate the list contents (add few hand picked crates from libz blitz). We would be willing to provide similar js resource for libz-blitz crates on libz-blitz side.

Open questions:
- How to handle crates which would normally require less restricted environment such as resources network. Would these be compilable but not runnable? Should there be a distinction in the list?

**Comment by budziq** [comment]
Hi, @shepmaster 

Sorry to let the subject stale so much. I was pretty swamped for a week after holidays. 
But I'm ready to do some real work now (If you would be willing to answer some questions about the code-base now and then).  

Where should the whitelist reside? In the top-crates (there is already a BLACK_LIST there)?

**Comment by shepmaster** [comment]
> Where should the whitelist reside? In the top-crates (there is already a BLACK_LIST there)?

I've got PR #197 open now, this would allow adding `additions = [ ... ]` to the new TOML file I've created. How does that look to you?

**Comment by budziq** [comment]
Awesome! The PR is exactly as I would like it :+1:
