### ISSUE TITLE
Implied "main" function

### ISSUE THREAD

**Issue by carlomilanesi** [integer32llc/rust-playground#169]
I think it would be great that if the code does not contain a top-level "main" function, implicitly the string "fn main() {" were added before the code, and the string "}" were added after the code, before passing the code to the compiler.
For example, if the file contained the lines:

```rust
let a = 12;
print("{}", a);
```

it would be compiled as it were:

```rust
fn main() {
let a = 12;
print("{}", a);
}
```

That would avoid some typing.

**Comment by shepmaster** [comment]
One thing that came up in #201 is that doing this would cause line and/or column numbers of error messages to be incorrect.

**Comment by carlomilanesi** [comment]
Perhaps, you could filter the compiler output and replace lines matching
--> src/main.rs:line:column
with an appropriate line number.
