### ISSUE TITLE
"LLVM IR" just shows "Unable to locate output file" if there is a compilation error

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#173]
## Steps to reproduce

Enter some code that makes rustc fail. Press "LLVM IR" (or "MIR" or "ASM").

## Expected behavior

The playground should show the error message produced by the compiler.

## Actual behavior

It just shows "Unable to locate output file". Not very helpful, it's not even clear that this is my fault (as opposed to something having gone wrong on the server side).

**Comment by shepmaster** [comment]
Ah, I never experience this because I never enter incorrect code (heh).

**Comment by RalfJung** [comment]
Yay, thanks :)
