### ISSUE TITLE
Expand regex to match #![crate_type = "lib"] on any line

### ISSUE THREAD

**Issue by TimNN** [integer32llc/rust-playground#181]
With the old playground one could use `#![crate_type = "lib"]` to easily get the IR / ASM of a function. Now this appears to be no longer possible.

**Comment by shepmaster** [comment]
It works, just the regex is a little stiff. Try `#![crate_type="lib"]` for now.

**Comment by TimNN** [comment]
Thanks, that works although only if the `#![crate_type]` is in the *first* line of code. (Which is kind of surprising).

**Comment by shepmaster** [comment]
> Which is kind of surprising

Not when you write sloppy regexes like I do, evidently!
