### ISSUE TITLE
Deployed rustfmt version is too old for specialization

### ISSUE THREAD

**Issue by adrianheine** [integer32llc/rust-playground#187]
See rust-lang-nursery/rustfmt#1112.

**Comment by shepmaster** [comment]
I don't understand. Using the code from the issue you linked:

```rust
impl<T, C> Foo<T, C> for () {
    default fn len(&self) -> isize {
        2
    }
}

impl<T> Foo<T, ()> for () {
    fn len(&self) -> isize {
        0
    }
}
impl Foo<i32, ()> for i32 {
    fn len(&self) -> isize {
        1
    }
}
```

The `default` keyword is not removed. 

Please review some guides on how to report a bug. This issue does not contain important things like:

1. What you did
1. What you expected
1. What actually happened.

**Comment by adrianheine** [comment]
Sorry, I should have been more thorough by actually testing different usages of `default`. This is indeed a bug in current `rustfmt` version, so I opened rust-lang-nursery/rustfmt#1823. Sorry again for the noise.

**Comment by shepmaster** [comment]
Sounds good. For reference, we [grab the current version of rustfmt on crates.io](https://github.com/integer32llc/rust-playground/blob/bc42662817a1c160574fa1d72384add0a15f6906/compiler/build.sh#L36-L38) every night. We **should** thus always be up-to-date (or ~24 hours behind, I suppose).
