### ISSUE TITLE
Allow compiling lib.rs code without main

### ISSUE THREAD

**Issue by dtolnay** [integer32llc/rust-playground#201]
Often I paste code from forum discussions or IRC into the playground to quickly look at an error message or check that it works. In these cases I need to throw a `fn main() {}` at the bottom.

If there is no main function, I would like it if the **Run** button could change into a **Compile** button and compile the code as a lib.rs.

This would be mutually exclusive with #169.

**Comment by shepmaster** [comment]
I assume adding `#![crate_type="lib"]` at the top is equally distasteful?

**Comment by dtolnay** [comment]
Correct. I think this issue is about doing what the user intended. Imagine if the playground were a snail-mail service where users mail in an envelope of Rust code, a person opens it and handwrites a response (error message or runtime output) and mails it back. If I mail in [this program](https://play.rust-lang.org/?gist=f16856675fa06743f4a9907b188e3fb8):

```rust
fn invoke(f: fn(&'static i32)) {
    f(&42);
}
```

No sentient human would send back a response saying "haha loser you forgot the main function." What I probably wanted to see was whether a reference to a literal can be 'static, so a better response would be:

```
error[E0597]: borrowed value does not live long enough
 --> src/main.rs:2:8
  |
2 |     f(&42);
  |        ^^ - temporary value only lives until here
  |        |
  |        does not live long enough
  |
  = note: borrowed value must be valid for the static lifetime...
  = note: consider using a `let` binding to increase its lifetime
```

**Comment by shepmaster** [comment]
> what the user intended

My main concern is that there are many types of users. Two primary ones that I believe exist for the playground:

1. People *just* starting with Rust that want to see what it's all about.
1. People more experienced with Rust that want to do "expensive linting". 

I think you and I are in the second category, but I wonder what experience the people in the first category would have with such a proposed UI change. I'd be worried about losing them by having their valid code compile and apparently do nothing.

There's also the "hey, I'm rustdoc / the Rust homepage / etc. and I want you to run some code" but those seem irrelevant to this concern.

> No sentient human would send back a response saying "haha loser you forgot the main function."

I think I know what you might say, but why couldn't the same logic be applied to `rustc` and/or cargo itself?

**Comment by shepmaster** [comment]
One possible solution is to have another config option that changes the existing logic that looks for the `crate_type` attribute. It could then behave as you are suggesting.

Another is to add the semi-dreaded dropdown on the **Run** button that allows people to forcibly choose if they want to run / build / test.

Both of these would add overhead for the advanced users.

**Comment by dtolnay** [comment]
In rustc's case it really is an error if you write main.rs without a main function. In the playground it is less clear-cut that what you are writing is a main.rs. Rust code goes in and compiler output comes out. I agree that there could be ways to improve that experience on rustc's end but I think there is value in handling this better in the playground regardless of what happens in rustc and/or cargo.

I would prefer no config option or dropdown just because we don't need the user to tell us whether or not they wrote a main function -- we should be able to tell (with some caveat for a main function generated by a macro, but still I think it is a solvable problem).

I wouldn't worry about losing newcomers by having their valid code compile and apparently do nothing. There are some UI aspects to figure out but I don't think that is a real risk if done right. For example a message:

> Your code compiled successfully! [Add a \`main\` function to make it runnable.](#)

Clicking the link appends an empty main and puts the cursor in the right place.

```rust
fn main() {
    ▓
}
```

**Comment by shepmaster** [comment]
> This would be mutually exclusive with #169.

If we followed #169, would it have a similar outcome? A quick check shows it would produce the same error (modulo line / column numbers!):

```rust
fn main() {
fn invoke(f: fn(&'static i32)) {
    f(&42);
}
}
```

**Comment by dtolnay** [comment]
Yes in that case but not in general, such as for this code:

```rust
#[macro_use]
extern crate serde_derive;

#[derive(Serialize)]
struct Shepmaster;
```

```
error[E0468]: an `extern crate` loading macros must be at the crate root
 --> src/main.rs:3:1
  |
3 | extern crate serde_derive;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by gnzlbg** [comment]
+1, I'd like to be able to just copy paste a function into the playground and generate the ASM code without having to write `fn main() { }` and then try to avoid the function from being eliminated completely in release.

**Comment by Centril** [comment]
My preferred approach would be to have the playground just emit a warning if you press `Run` and there is no `fn main() {..}`. That way, you can clearly see from the output that nothing was executed, but things still compile.
