### ISSUE TITLE
Vim mode

### ISSUE THREAD

**Issue by vignesh-sankaran** [integer32llc/rust-playground#206]
Would be cool if we had a vim mode for the editor.

**Comment by CYBAI** [comment]
There is `vim` mode.
Check `Editor Keybinding` inside `Config`.

![image](https://user-images.githubusercontent.com/6782666/29865790-0a8a7828-8da9-11e7-94fb-62d18942f627.png)

**Comment by vignesh-sankaran** [comment]
Thanks @CYBAI
