### ISSUE TITLE
Link to currently-selected channel's error index instead of always stable

### ISSUE THREAD

**Issue by gnzlbg** [integer32llc/rust-playground#207]
When I get an error with a nightly feature, like here:

https://play.rust-lang.org/?gist=4d64bf772c792d3975ad4e9f998eb20b&version=nightly

And I click on the explanation, it sends me to a page that doesn't contain it. 

Maybe it should be sending me to some nightly docs page when using nightly? https://doc.rust-lang.org/nightly/error-index.html#E0564

instead of

https://doc.rust-lang.org/error-index.html#E0564

Note that, for some reason, the nightly index doesn't have E0564 in this case either...

**Comment by shepmaster** [comment]
I think there are two coupled problems here, but only one that we have the power to fix here:

> Maybe it should be sending me to some nightly docs page when using nightly?

Yes, picking the right channel to link to makes sense. I'm going to change this issue to reflect that.

> for some reason, the nightly index doesn't have E0564 in this case either...

That's going to be the bigger issue — we can't make error descriptions magically appear 😸 I think it's *technically possible* to have a giant list of what errors have descriptions in which channels and then only link the right ones... but that seems like a *lot* of work when errors should be documented to start with.

**Comment by gnzlbg** [comment]
@shepmaster 

> we can't make error descriptions magically appear

Yes, I did not want to meant this. I've added this request to the corresponding issue in rust-lang/rust.
