### ISSUE TITLE
No space left on device error

### ISSUE THREAD

**Issue by LeopoldArkham** [integer32llc/rust-playground#215]
Someone [posted this](https://www.reddit.com/r/rust/comments/756j8w/hey_rustaceans_got_an_easy_question_ask_here/dobxb9i/) on reddit, repeating it here in case you come by first.

Compilation fails with:

> error: failed to link or copy `/playground/target/debug/build/dbghelp-sys-abba937303e0d19e/build_script_build-abba937303e0d19e` to `/playground/target/debug/build/dbghelp-sys-abba937303e0d19e/build-script-build`

> Caused by:
  No space left on device (os error 28)

**Comment by shepmaster** [comment]
Oops, thanks! Ever since we added more crates, that instance runs out of disk a lot more quickly. I'm slowly (read: lazily) moving to a larger EC2 instance, but until then I have to clean up some junk every so often.
