### ISSUE TITLE
Anonymous gists may be retired

### ISSUE THREAD

**Issue by kivikakk** [integer32llc/rust-playground#218]
Hi there! I'm a Rustacean who is also a GitHubber, and it looks like we may be retiring anonymous gists in the future. Given the Playground's current reliance on saving to anonymous gists, I thought it'd be good to give a heads up here. (One quickly implementable workaround that comes to mind is creating an account for the Playground for its gists.)

Maybe related to #166 and some proposals there.

**Comment by shepmaster** [comment]
Thank you for the heads-up! Is there somewhere where I can find more information about this? What does "retiring" entail — will all anonymous gists be disappearing? Will old ones still exist but new ones can no longer be created? One worry about a created account is rate limiting; I don't know the current rate of sharing, but I'd be worried about hitting the limits I'm aware of.

**Comment by kivikakk** [comment]
The decision is still in the works (it's currently a massive spam vector), but once it becomes officially we'll likely make a blog post with a timeline. Nothing is finalised yet, but I'm fairly sure we'll keep old ones around and simply stop new ones.

We can definitely work out something around rate limiting, and will likely look to make a general solution here too.

**Comment by kivikakk** [comment]
A little bump on this; it's nearing completion. (There'll almost certainly be an announcement with some lead time given, but wanted to keep everyone updated here seeing as I opened this issue and the Playground is just so useful!)

**Comment by davidtwco** [comment]
GitHub have announced [in a blog post](https://github.com/blog/2503-deprecation-notice-removing-anonymous-gist-creation).

**Comment by shepmaster** [comment]
@kivikakk Is there anything in particular I need to do / someone to talk to about setting up accounts for the playground? There are two primary instances of the playground (https://play.rust-lang.org/ and https://play.integer32.com/); presumably each should have an account under their respective organizations. Is that even a thing; an "organization account"?

**Comment by kivikakk** [comment]
There's no "user" account for an organization which can do things like authenticate; you'll need an OAuth token for a user with the `gist` scope; see https://developer.github.com/v3/gists/#authentication. What that user is/where it lives is up to you!

**Comment by shepmaster** [comment]
I've merged the fixes as part of #270, but have only deployed to play.integer32.com for right now to shake out any issues. I'll be deploying to play.rust-lang.org sometime this week (before the 19th!).

@kivikakk Is there any way I can see the user's gist rate *before* hitting the limit, so I could request an appropriate increase?

**Comment by shepmaster** [comment]
All deployed now, so... onwards!
