### ISSUE TITLE
Cannot scroll if started a new session

### ISSUE THREAD

**Issue by hcpl** [integer32llc/rust-playground#223]
After opening a new session, with horizontal splitting, I can't scroll vertically but can scroll horizontally - vice versa for vertical splitting.
Accessing the site via permalinks doesn't introduce this issue.

Steps to reproduce in horizontal splitting:
1. Open up a fresh page https://play.rust-lang.org/.
2. Type several lines so that the whole source doesn't fully fit in your screen.
3. Hit "Run".
4. Try to scroll up/down.

Steps to reproduce in vertical splitting:
1. Open up a fresh page https://play.rust-lang.org/.
2. Type a long line that doesn't fully fit in your screen.
3. Hit "Run".
4. Try to scroll left/right.

**Comment by shepmaster** [comment]
Aw, I think this is a regression — I thought that the upstream component fixed this. As a temporary workaround, resize the window; that should re-enable scrolling.

**Comment by hcpl** [comment]
Yeah, resizing helps, thanks!

Now that I checked again, I've found a more precise description of the issue (based solely on visual effects so I may be wrong): when panels are shown, it can still be scrolled. The bug is that it doesn't update dimensions of the text area after the panel pop up, so while the scrollbar technically _does_ hit the bottom/right edge of the text area, we see it like it was hitting the bottom/right edge of the window because the lower/right part is hidden behind the panel.

This can explain why opening a page via permalinks still works - panels are popped up by default and dimensions are in sync, so scrollbars work as expected.

**Comment by shepmaster** [comment]
If you are interested in the relevant code change, you can see [where I removed it recently](https://github.com/integer32llc/rust-playground/commit/beea75a94bce22d77db8187ce3ce6e80db7c10df). I'm going to be putting a much better comment explaining the problem when I fix it this time ;-)

**Comment by shepmaster** [comment]
I got misled by the React-Ace [changelog entry](https://github.com/securingsincity/react-ace/blob/master/CHANGELOG.md):

> Resize on component did mount and component did update

But this doesn't apply in our case (no new property came in, and it was already mounted). However, I think we can cheat and pass in a property corresponding to the display status of the lower pane and then use that to automatically trigger the resize instead of doing it ourselves.

**Comment by hcpl** [comment]
The fix looks good, and it works for me, thanks!
