### ISSUE TITLE
Highlight `dyn` as a keyword

### ISSUE THREAD

**Issue by vi** [integer32llc/rust-playground#224]
[dyn] is already [implemented in nightly][iss], so maybe `dyn` should be highlighted somehow in the playpen?

[dyn]:https://github.com/rust-lang/rfcs/pull/2113
[iss]:https://github.com/rust-lang/rust/issues/44662

**Comment by shepmaster** [comment]
> should be highlighted somehow

Syntax highlighting is provided by ACE — perhaps you'd be willing to submit a pull request to them?

> in the playpen?

There is no playpen. There is only the playground.

**Comment by vi** [comment]
"Rust Playpen" =? "The Rust Playground" =? "play.rust-lang.org site".

**Comment by shepmaster** [comment]
Sounds good, vim [sic]. Names have meanings and differences; the *very old* site was called the playpen.

**Comment by vi** [comment]
Only now realized [the difference](http://wikidiff.com/playpen/playground).

**Comment by shepmaster** [comment]
Thank you for opening an issue on Ace. Once there's a corresponding PR, I can probably hack up the existing Rust highlighter using the diff. I just don't want to be forced into maintaining a perpetual fork of an open source project without very good reason.

**Comment by vi** [comment]
The PR has been merged.
