### ISSUE TITLE
Investigate supporting WASM target

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#232]
Alex suggests we need:

1. a wasm target
2. a thing that disassembles a binary wasm file to a "wast" file or "wat"

The "asm" output of llvm is not at all the "wat" format but the "wat" format is the "official" one

We should also garbage-collect the WASM to make it look better.

**Comment by shepmaster** [comment]
One concrete problem: If we run `--target=wasm`, then **all** of the crates will need to be built for wasm in addition to x86-64.

**Comment by alexcrichton** [comment]
Oh dear :(

Is there a way we could just whitelist a few for wasm perhaps?

**Comment by shepmaster** [comment]
Certainly possible. Do you have such a list?

FWIW, I'm close to getting it to work with the Docker containers and no dependencies.

**Comment by alexcrichton** [comment]
Oh I'd go with the empty list as a whitelist to start out with :)

In the sense of allocation in the standard library is probably as far as we need to go for now. Also awesome! That wouldn't happen to be a branch I could poke at, would it?

**Comment by shepmaster** [comment]
> a branch I could poke at,

Sure, I just pushed https://github.com/integer32llc/rust-playground/tree/wasm — beware that it probably doesn't *really* work yet. I've it hacked up so that clicking `MIR` does the wasm code.

To get the container, do something like:

```
cd compiler
CHANNELS_TO_BUILD=nightly TOOLS_TO_BUILD="" ./build.sh
```
