### ISSUE TITLE
Enable edition selection

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#260]
Will be activated via `epoch = 2018` in Cargo.toml

Since future compilers will support multiple epochs, this makes sense to have as a UI item, instead of just a temporary `#![feature]` flag.

My first thought is to add a new configuration option:
- `default`,
- `2018`,
- `2015`

Selecting `2018` will need to only allow (AND automatically select) nightly to start with, then trickle to beta / stable. Until then, default is `2015`.

This will require that the playground gain the ability to modify the Cargo.toml. We already hack it up for WASM, so that should be cleaned up too.

**Comment by Manishearth** [comment]
We can also pass this down via RUSTFLAGS

**Comment by shepmaster** [comment]
Note to self: URLs loading code need to default to 2015, loading the fresh playground should use default. The value needs to be preserved in local storage as well.
