### ISSUE TITLE
Playground panics when `termination_trait` returns Ok(())

### ISSUE THREAD

**Issue by U007D** [integer32llc/rust-playground#263]
FYI, I tried using the `termination_trait` feature on [Playground](https://play.rust-lang.org/?gist=cfca12a46cea08d53a95591120b5a9d8&version=nightly) but it `panic`s:

```
Compiling playground v0.0.1 (file:///playground)
thread 'rustc' panicked at 'assertion failed: !substs.has_erasable_regions()', librustc_trans_utils/symbol_names.rs:192:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (27a046e93 2018-02-18) running on x86_64-unknown-linux-gnu

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```
This above is  code from [the run-pass test](https://github.com/rust-lang/rust/blob/e8f03b9438d6516fd7067cfda2f09c925d6d92f2/src/test/run-pass/rfc-1937-termination-trait/termination-trait-for-result-box-error_ok.rs), which passes, and running the same code running locally on my machine also compiles and runs successfully.

**Comment by shepmaster** [comment]
I don't believe this to be related to the playground. Notably, I can reproduce this using the nightly on my macOS laptop:

```
$ rustc --version --verbose
rustc 1.24.0 (4d90ac38c 2018-02-12)
binary: rustc
commit-hash: 4d90ac38c0b61bb69470b61ea2cccea0df48d9e5
commit-date: 2018-02-12
host: x86_64-apple-darwin
release: 1.24.0
LLVM version: 4.0

$ cargo +nightly run
   Compiling term v0.1.0 (file:///private/tmp/term)
thread 'rustc' panicked at 'assertion failed: !substs.has_erasable_regions()', librustc_trans_utils/symbol_names.rs:192:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (27a046e93 2018-02-18) running on x86_64-apple-darwin

error: Could not compile `term`.

To learn more, run the command again with --verbose.
```

**Comment by shepmaster** [comment]
Specifically, the latest nightly has a commit hash of rust-lang/rust@4d90ac38c0b61bb69470b61ea2cccea0df48d9e5, but your commit was rust-lang/rust@e8f03b9438d6516fd7067cfda2f09c925d6d92f2. It appears no nightly has been created with your commit yet.

**Comment by U007D** [comment]
Ah, I was wondering if propagation delay was playing a part in this--I'll open an issue against the compiler.

Thanks, @shepmaster.
