### ISSUE TITLE
Investigate moving to a new web framework

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#269]
Iron is no longer actively maintained. Now is when we can see if our architecture separation pays off or not...

# How can I help?

In order of difficulty from easy to hard...

- 👍 or 👎 a comment for a framework that you like or dislike **for any reason**.
- Let us know of a web framework that's worth investigating that we don't have listed.
- Add a comment if you research one or more of the requirements for a framework.
- Attempt porting the playground to a framework and push up a branch.

# What are you looking at?

- [Actix web](https://github.com/integer32llc/rust-playground/issues/269#issuecomment-558197740)
- [Gotham](https://github.com/integer32llc/rust-playground/issues/269#issuecomment-370269044)
- [Thruster](https://github.com/integer32llc/rust-playground/issues/269#issuecomment-558198613)
- [Tide](https://github.com/integer32llc/rust-playground/issues/269#issuecomment-558198835)
- [Tower Web](https://github.com/integer32llc/rust-playground/issues/269#issuecomment-558197248)
- [Warp](https://github.com/integer32llc/rust-playground/issues/269#issuecomment-558197388)
- [Axum](https://github.com/integer32llc/rust-playground/issues/269#issuecomment-890335877)

# Requirements

- Caching
  - Aggressive caching
  - Fine-grained caching (index.html vs assets)
- Static file serving
  - Modification time checking
  - No [path traversal](https://www.owasp.org/index.php/Path_Traversal)
  - Side-by-side pre-compressed files
  - Automatic content-type assignment
- Redirection of HTTP to HTTPS (optional)
- Basic off-request access logging (url, ip, status, start, duration)
- Routing
  - With path variables
- URL rewriting
- CORS
- JSON body parsing / response

## Caching

The playground serves up `index.html` and a few other similar files that never change name. These should ideally use something like ETags with a short-ish expiry. We currently use a 1 hour expiry, but not ETags.

The assets are all in a path called /assets. These all have a digest hash appended to them, so they can be cached "forever". In practice, this is 1 year.

There's a few other pieces of information that could use caching (e.g. the playground crates, channel versions) but these are all generated data and so we could pre-compute an ETags identifier to check against.

# Access statistics

- Roughly 2 requests per second

**Comment by shepmaster** [comment]
# Gotham

- Static file serving not present/complete https://github.com/gotham-rs/gotham/issues/55
- CORS not present/complete https://github.com/gotham-rs/gotham/issues/119

**Comment by fafhrd91** [comment]
did you consider [actix](https://github.com/actix/actix-web) ?

**Comment by shepmaster** [comment]
@fafhrd91 I have not really considered it. Speaking plainly, your incessant advertising of actix in almost every place I read about Rust (Gitter, Reddit, Hacker News, etc.) makes me less inclined to try it. I, so far, have no technical opinions about it and haven't ruled it in or out.

**Comment by fafhrd91** [comment]
fair point. in that case Gotham is better choice I guess.

**Comment by shepmaster** [comment]
# [Tower Web](https://crates.io/crates/tower-web)

To be determined...

**Comment by shepmaster** [comment]
# [Warp](https://crates.io/crates/warp)

To be determined...

**Comment by shepmaster** [comment]
# [Actix web](https://crates.io/crates/actix-web)

To be determined...

**Comment by shepmaster** [comment]
# [Thruster](https://crates.io/crates/thruster)

To be determined...

**Comment by shepmaster** [comment]
# [Tide](https://crates.io/crates/tide)

To be determined...

**Comment by shepmaster** [comment]
# [Axum](https://crates.io/crates/axum)

To be determined...

**Comment by shepmaster** [comment]
I've [merged in an implementation using Axum](https://github.com/integer32llc/rust-playground/pull/777). As of a few hours ago, I've enabled the Axum feature flag on `play.rust-lang.org`. Assuming nothing drastic happens that cannot be fixed, I'll eventually move completely over.

**Comment by shepmaster** [comment]
Closed in #799
