### ISSUE TITLE
Incorrect test/run button switch

### ISSUE THREAD

**Issue by AnthonyMikh** [integer32llc/rust-playground#274]
Currently button switches from 'Test' to 'Run' if `main` function is present, but for some reason playground searches it in the whole code... Including comments.
So this snippet compiles and works fine:
```rust
#[test]
fn do_tests() {
    println!("Pretending to do some tests...");
}
```
...while this one doesn't:
```rust
/* fn main() {} */
#[test]
fn do_tests() {
    println!("Pretending to do some tests...");
}
```
producing the following mistake: `error[E0601]: main function not found`
since playground finds `main` function while the compiler doesn't.

**Comment by shepmaster** [comment]
This is true. Unless someone wants to write a Rust parser in JS (which might already exist in some form for the syntax highlighting....), the regex that we have now is going to to have false positives.
