### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by RReverser** [integer32llc/rust-playground#277]
When trying to share a gist from Playground, I'm getting:

```json
{
  "message": "API rate limit exceeded for [MY IP]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

I guess it makes sense that it's possible to hit the limit given that playground uses client-side Github API, but it's the first time I'm seeing this.

I wonder what would be the correct way to fix this. Maybe add login via Github to the playground so that user could get higher limit of requests?

**Comment by shepmaster** [comment]
> given that playground uses client-side Github API,

It doesn't, anymore (#270). 

> Maybe add login via Github to the playground so that user could get higher limit of requests?

That's a possibility that I've been toying around with in the back of my head. I should probably make a separate issue for that...

**Comment by shepmaster** [comment]
> It doesn't, anymore

Well, I've only deployed to play.integer32.com; which deployment did you experience this on?

**Comment by RReverser** [comment]
It was on `play.rust-lang.org`, as far as I understood, this is still the correct repo to report issues to?

**Comment by shepmaster** [comment]
> this is still the correct repo to report issues to?

Yep, there's just two deployments. At this current point in time, they have *slightly* different releases of code, specifically regarding Gists. I was worried that you were reporting issues with the new code.

**Comment by shepmaster** [comment]
I'm going to close this for now, as we switched the Gist implementation. Thanks!

**Comment by tjpalmer** [comment]
> I'm going to close this for now, as we switched the Gist implementation. Thanks!

I know this is an old topic, but is there not still a rate limit for the server account that's saving gists?

**Comment by shepmaster** [comment]
> is there not still a rate limit for the server account that's saving gists?

GitHub [applies a rate limit for all requests](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28). The playground uses an authenticated connection. Does that answer your question? Are you experiencing a problem?

**Comment by tjpalmer** [comment]
> GitHub [applies a rate limit for all requests](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28). The playground uses an authenticated connection. Does that answer your question? Are you experiencing a problem?

No, sorry, no problem. I'm trying to build something similar, and I figured y'all would likely easily exceed rate limits, so I was wondering if you've hit issues ever and if so, how you've addressed them. I suspect you get a lot of usage.

**Comment by tjpalmer** [comment]
> > likely easily exceed rate limit
> > suspect you get a lot of usage.
> 
> I actually don't know that we do. I don't think we track number of requests to the gist endpoints, but skimming through the error logs, I don't see many errors for creating a gist, and none for rate limit reasons.

Thanks much for the info!
