### ISSUE TITLE
UI broken in Safari, can't see output

### ISSUE THREAD

**Issue by killercup** [integer32llc/rust-playground#28]
The output is not visible in Safari (its height is 5px or something). If I change a random CSS property of `.output`, it seems to recalculate the height and corrects the layout.

I'm using Safari Technology Preview version 9.1.2 (11601.7.4, 11602.1.37).

**Comment by shepmaster** [comment]
Hmm. Appears to be ok in 9.1.1:

![image](https://cloud.githubusercontent.com/assets/174509/16926672/c5965608-4cf7-11e6-8ea0-d87d6fb9c560.png)

Could you attach a screenshot?

**Comment by killercup** [comment]
This happens when I go to <http://play.integer32.com> and just press "Run":

![rust_playground](https://cloud.githubusercontent.com/assets/20063/16926755/6f16a732-4d2a-11e6-9edd-4eea4df3ef83.png)

If it works for you on 9.1.1 it's probably broken because of the tech preview. Which is weird, because I also think it's the first Safari version to support `display: flex` without a prefix, so in theory it should work better. ¯\_(ツ)_/¯

**Comment by shepmaster** [comment]
> to support display: flex without a prefix

I do recall there being issues because I originally did not use a prefix, but it certainly seems strange that Safari itself updating to not need the prefix would cause an issue like this. I wonder how hard it is to test with multiple Safari versions...

**Comment by shepmaster** [comment]
Let's leave this open until 9.1.2 comes out, and hope that it magically fixes itself. @killercup if you have access to a TP, does that mean you can file radar issues? Maybe that would be worth doing?

**Comment by killercup** [comment]
Oh, i'm stupid. Safari Technology Preview doesn't replace Safari itself, I still have 9.1.1 installed. And it looks great in it!

I'd say this is a bug in the Safari Preview itself. It's a public beta, I'll see if I can get that feedback to Apple in some way.

**Comment by shepmaster** [comment]
SIGH. It didn't get magically fixed.

![image](https://cloud.githubusercontent.com/assets/174509/18835142/a535bd20-83c7-11e6-954a-282eec8fc429.png)

**Comment by shepmaster** [comment]
Sigh, this has to be something broken in Safari. If I open up the element inspector in Safari and cycle the `flex` rule off and then on, everything looks fine. So there's no real change in the CSS or the markup to make this work. Without knowing anything about browsers, I'm going to guess that when we add the element to the page, there's no recalculation of the sizes of elements with regards to  flexbox.

![image](https://cloud.githubusercontent.com/assets/174509/19398137/2be56b04-9219-11e6-9e9d-a2406ccde317.png)

**Comment by shepmaster** [comment]
@killercup did you ever file anything with Apple?
