### ISSUE TITLE
Capture file operation key shortcuts

### ISSUE THREAD

**Issue by Bert-Proesmans** [integer32llc/rust-playground#294]
I don't know the policy on capturing key combos within the playground.
The idea came from personally struggling, so I'm strongly biased.

Because of muscle memory the key combination [Ctrl] + [S] is pressed about 5 times per session. This opens the save file dialog for completing the task of saving the current page (HTML) and loaded resources to the local disk.
Is it possible to catch these key combo events within the playground and prevent them from bubbling up to the browser? Is this (semantically) correct to do? Are there other file operation shortcuts which might benefit from capturing?

Why?
The playground looks like an editor and feels like a mini-IDE. Capturing specific file operation key combos might become semantically correct for this reason. The browser (tab) is repurposed to be a code editor.

**Comment by shepmaster** [comment]
> Is it possible to catch these key combo events within the playground and prevent them from bubbling up to the browser? Is this (semantically) correct to do? Are there other file operation shortcuts which might benefit from capturing?

Yes, [it's possible](https://github.com/integer32llc/rust-playground/blob/76366854f60c4c2063006823f755bd92f5a0ee41/ui/frontend/AdvancedEditor.tsx#L50-L52) to capture specific types of keychords.

**Comment by shepmaster** [comment]
Support for this will probably happen after the header rewrite and corresponding shortcuts for the tools.
