### ISSUE TITLE
Show versions of Clippy / Rustfmt / Miri

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#300]
Spawned from #184. 

This should probably include the *Rust* version as well, since it can be decoupled from what's in the nightly.

**Comment by lqd** [comment]
For anyone wanting to pick this up, here's some more information.

There's the `rustfmt -V` option to return its version, in a format very similar to `rustc -V`, for example `0.3.6-nightly (e0e3e22 2018-01-18)`. (I wasn't able to try with clippy at this point)

Adding support for this could be similar to how the playground gets the channels' rustc version.

For example, for the server-side backend, the stable version endpoint is [here](https://github.com/integer32llc/rust-playground/blob/master/ui/src/main.rs#L204-L210), and the code asking `rustc` for its version on a given channel, and parses the results into its components is [here](https://github.com/integer32llc/rust-playground/blob/master/ui/src/sandbox.rs#L224-L245).

Client-side, there are different [routes](https://github.com/integer32llc/rust-playground/blob/master/ui/frontend/actions.ts#L25-L29) defining the previously mentioned endpoints. These are used in the `performVersionsLoad` function [here](https://github.com/integer32llc/rust-playground/blob/master/ui/frontend/actions.ts#L609-L627), which is called when the app starts up, ultimately storing the resulting versions in the app state [here](https://github.com/integer32llc/rust-playground/blob/master/ui/frontend/reducers/versions.ts).
