### ISSUE TITLE
Add ability to resize output window

### ISSUE THREAD

**Issue by Dowwie** [integer32llc/rust-playground#302]
Feature request:  ability to resize the output window

**Comment by TNkemdilim** [comment]
Don't know if any one is currently working on it? The branch link you shared doesn't exist :(

I could hop on it though.

**Comment by shepmaster** [comment]
> if any one is currently working on it

There's nothing active as far as I know; I don't think you need to worry about stepping on anyone's toes for a conflicting implementation. 

Please play around a bit with the code to establish a bit of familiarity then post a rough sketch of how you plan on approaching the solution. I'll try to give any early feedback or suggestions on the approach to try and minimize any rework.

**Comment by TNkemdilim** [comment]
I just played around with it locally using [split.js](https://github.com/nathancahill/split) (~2kb in size), and seems to be working well so far.

Although, if you're keen on an implementation without any dependency, I could try to work something out.
