### ISSUE TITLE
Offer adding features to the code with one click

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#317]
Link this up to add it to the code:

```
help: add #![feature(try_from)] to the crate attributes to enable
```

**Comment by Centril** [comment]
This would be very useful to me, either to automatically add it to the text or on click (former is my preference).

**Comment by shepmaster** [comment]
> automatically add it to the text

I have zero interest in the playground ever automatically changing the user's code. 

Remember that my primary target audience for the playground is not advanced type theorists that write RFCs for fun or people who write compilers; it is for the person who is new to Rust and wants to learn what it's all about. Automatically changing their code removes a large chunk of learning and would actively set them up for failure when they aren't using the playground. 

If the Rust compiler itself starts automatically rewriting code, then it seems entirely feasible for the playground to follow suit.

**Comment by Centril** [comment]
A button would also be useful :)
