### ISSUE TITLE
Help page lists uncompilable example

### ISSUE THREAD

**Issue by Thiez** [integer32llc/rust-playground#318]
So, when visiting the help page (https://play.rust-lang.org/help) the very first example doesn't compile! The example uses the 'rand' crate, but this crate is not supported in the playground. The example in question:

```rust
extern crate rand;
use rand::Rng;

fn main() {
    let mut rng = rand::thread_rng();
    println!("{}", rng.gen::<u8>());
}
```

The relevant code seems to be in [ui/frontend/Help.tsx](
https://github.com/integer32llc/rust-playground/blob/5546360191ec5cfe8b162a97bd7917b1dfb5c29c/ui/frontend/Help.tsx#L23-L29).

**Comment by Thiez** [comment]
Searching around some more I guess [this commit](https://github.com/integer32llc/rust-playground/commit/677029e0582c704d0d16409cce892f6d39c6cfea) is to blame.

**Comment by shepmaster** [comment]
Heh, that's an embarrassing side effect of that. They've released a new version that compiles again, so I've updated the crates (#319). In an hour or so it should be working again.

**Comment by oberien** [comment]
It works again on play.rust-lang.org.

**Comment by shepmaster** [comment]
For good measure, I've also opened #320 to avoid prerelease crates in the future (which is why I had to ignore rand for a bit)
