### ISSUE TITLE
Support configuring stdin runtime data

### ISSUE THREAD

**Issue by randfur** [integer32llc/rust-playground#329]
It would be nice to test runtime behaviour without the complier optimising away constant expressions, using stdin would be a convenient way of doing this.

**Comment by oberien** [comment]
You could also achieve your intended behaviour by writing your values to a file, then reading from that same file again.

**Comment by shepmaster** [comment]
Thank you for the suggestion, but I believe that it is already covered in #22 .

**Comment by shepmaster** [comment]
I've also used random numbers for a similar mechanic.
