### ISSUE TITLE
The execution output will highlight fake errors and warnings

### ISSUE THREAD

**Issue by kennytm** [integer32llc/rust-playground#340]
Demo:

```rust
fn main() {
    let _: std::error::Error = "warning:🤔...";
}
```

![screenshot_2018-06-18 17 28 45_gscxcz-fs8](https://user-images.githubusercontent.com/103023/41529186-d3e70ea6-731e-11e8-8b5c-20e41189a545.png)

This also affects runtime output to stderr e.g.

```rust
fn main() {
    eprintln!("warning:🤔...\nerror[E9999]:👀...");
}
```

**Comment by shepmaster** [comment]
Yup. It's all powered by [regex-based syntax highlighting](https://github.com/integer32llc/rust-playground/blob/811143311ca1977c84b69e57399c799b4914d980/ui/frontend/highlighting.ts#L4-L15). Any suggestions on how to improve it?

**Comment by kennytm** [comment]
A partial solution would be to make warnings and errors to match the start of line

```js
Prism.languages.rust_errors = { // eslint-disable-line camelcase
  'warning': /^warning:.*/m,
  ...
```

This will stop highlighting `std::error::Error` which would be good enough for me. Users can still perform the `eprintln!` trick but that's not really a real problem 😄.

----

Alternatively we could run `cargo` with `--color always` and parse the ANSI escape code manually 😛

**Comment by shepmaster** [comment]
> match the start of line

As I was submitting, I realized that would probably be the right step, but I figured I'd let you tell me if there was something better. Isn't there some JSON output or something?

> we could run cargo with --color always and parse the ANSI escape code manually

I think thats the way ye olde playground worked, actually. I'm sure there's a JS library that does it for us too. I wasn't a super fan of trying to deal with that though.

**Comment by shepmaster** [comment]
> `'warning': /^warning:.*/m,`

Hmm, I used `/^warning:.*$/m,`. Do you know if having the `$` is good/bad here? I'm surprised it seems to work *without* it... but I guess it just goes to the end of the line?

**Comment by kennytm** [comment]
@shepmaster A `.` will not match new lines, so it is fine without the `$`.

**Comment by shepmaster** [comment]
K. Then I'll use the `$` just because it's more immediately obvious at first glance.
