### ISSUE TITLE
Ctrl+F does not work within the ACE editor

### ISSUE THREAD

**Issue by kennytm** [integer32llc/rust-playground#347]
When the "ace" editor is selected, hitting Ctrl+F (⌘F on macOS) will do nothing. 

The web console suggests it tries to load https://play.rust-lang.org/ext-searchbox.js but the file does not exist (it should be a copy of https://github.com/ajaxorg/ace-builds/blob/master/src-min/ext-searchbox.js).

**Comment by shepmaster** [comment]
Who needs to search code? Don't you just *know* where it is?

**Comment by shepmaster** [comment]
As a silly "workaround", you can click outside the editor and use the browsers find. This will only work for the visible code though.

**Comment by shepmaster** [comment]
Got a local fix, just want to see how much bigger it makes the bundle.

**Comment by kennytm** [comment]
@shepmaster

> Who needs to search code? Don't you just know where it is?

When you open a playground link which the code has multiple pages 🙂

**Comment by shepmaster** [comment]
Huh. Do you see this in the playground? I see it in local development, but it doesn't appear to show up when deployed...

**Comment by shepmaster** [comment]
Oh, wow. It's "clever" and obeys the key binding setting (ace / emacs / vim)

**Comment by kennytm** [comment]
I can see this in the integer32 playground. Not in the rust one yet.

**Comment by shepmaster** [comment]
> Not in the rust one yet.

Do you have a keybinding set there? If so:

- Ace: <kbd>control</kbd> - <kbd>f</kbd>
- Emacs: <kbd>control</kbd> - <kbd>s</kbd>
- Vim: <kbd>/</kbd>

**Comment by kennytm** [comment]
OK works now, I guess it's just cache.

**Comment by shepmaster** [comment]
> just cache.

Yeah, there's a strong cache (IIRC 24h for the index page, ∞ for any asset), so you sometimes need to force a reload to get that new-new.
