### ISSUE TITLE
cannot paste into code editor on android

### ISSUE THREAD

**Issue by lazybean** [integer32llc/rust-playground#353]
Firefox android: A long press into the text field does not show the contextual menu that let me paste.

Chrome android: I see the contextual menu but tapping paste does not paste anything

**Comment by lazybean** [comment]
May be more an issue with the ace editor though.

i was hoping to paste does code snipet from the rust book.

**Comment by sunjay** [comment]
I believe this is an issue with ace editor. If you click on "Config" and click "Simple" (under Style), you can edit normally in a regular textarea.

**Comment by lazybean** [comment]
@sunjay Thanks, changing the style to "Simple" in "Config" fixes it!
