### ISSUE TITLE
Use the "serde" feature on the chrono crate.

### ISSUE THREAD

**Issue by davidtwco** [integer32llc/rust-playground#360]
Both `serde` and `chrono` are crates currently available on the playground, it would be great if [the "serde" feature in chrono](https://github.com/chronotope/chrono/blob/master/Cargo.toml#L34) was enabled so that these crates can be used together on the playground.

**Comment by shepmaster** [comment]
You'll have to ask chrono to add [playground-specific metadata](https://github.com/integer32llc/rust-playground/issues/192#issuecomment-388589736).
