### ISSUE TITLE
Make the "Run" menu remember the selection

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#368]
When I am using the non-"Run" modes in the "Run" menu, like generating assembly or LLVM IR, I usually don't do that just once. I write some code, ask for the IR, but then there's a type error so I fix that, ask for the IR, see something, tweak the code, ask for the IR again to see the effect that has, and so on.

Currently, every time I want to update, I have to go to the submenu again and find the right entry. It would be great if that menu could remember what I used, so I only have to click once for subsequent re-generation of the IR.

**Comment by shepmaster** [comment]
Hmm, I'm surprised that this issue doesn't already exist. We pretty much planned on adding this after the recent UI revamp; I guess you are the first person to care enough to actually file an issue!
