### ISSUE TITLE
Running clippy should not require a main function

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#382]
I tried running clippy on
```rust
use std::fmt::Debug;

pub fn test<T: Debug>(x: Vec<T>) {
    for t in x.iter() {
        println!("{:?}", t);
    }
}
```
Even though "Build" works just fine, clippy complains that there is no `main`.

**Comment by hellow554** [comment]
Is this a general clippy problem or a thing with the playground? (IIRC clippy is able to check libraries without main, right?)

**Comment by shepmaster** [comment]
> a thing with the playground

Basically, we need to pass information from the frontend to the backend that the code in question should be treated as a library. Somewhere around here is the right place:

https://github.com/integer32llc/rust-playground/blob/f103d06cfb4c96ca6055ae9f4b16ca5cca03c852/ui/frontend/actions.ts#L470-L471

Then the corresponding data needs to be parsed:

https://github.com/integer32llc/rust-playground/blob/f103d06cfb4c96ca6055ae9f4b16ca5cca03c852/ui/src/main.rs#L633-L636

And acted upon:

https://github.com/integer32llc/rust-playground/blob/f103d06cfb4c96ca6055ae9f4b16ca5cca03c852/ui/src/sandbox.rs#L200-L201
