### ISSUE TITLE
`pub fn main` fails to be seen as a `main` function

### ISSUE THREAD

**Issue by turbulencetoo** [integer32llc/rust-playground#384]
```
pub fn main() {
    println!("Hello, world!")
}
```

Receives message 

> No main function was detected, so your code was compiled
> but not run. If you'd like to execute your code, please
> add a main function.

https://play.rust-lang.org/?gist=c18a0c4473c2421bac4437f7e9e9fbdf&version=stable&mode=debug&edition=2015

**Comment by shepmaster** [comment]
Thanks for the report!
