### ISSUE TITLE
Rework Miri build process

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#387]
Miri has a [toolchain file](https://github.com/solson/miri/blob/master/rust-toolchain) but we want to always try to use the latest nightly.

Look into marking these builds as allowable failures in Travis as well, instead of `|| true`.

**Comment by RalfJung** [comment]
> Look into marking these builds as allowable failures in Travis as well, instead of || true.

I assume this does not apply to miri only. Also, for reference:
https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail
