### ISSUE TITLE
Emit assembly comments in the disassembly

### ISSUE THREAD

**Issue by GabrielMajeri** [integer32llc/rust-playground#397]
Pull request rust-lang/rust#53290 added the (nightly only) option `-Z asm-comments`, which makes LLVM emit comments in the disassembly, making it much more readable.

It would be awesome if the Rust playground could enable this flag in the disassembly view (for nightly builds, at least until it stabilises), possibly unconditionally (I don't think it has any downsides).

For implementation, I think it might be enough to [add the flag here](https://github.com/integer32llc/rust-playground/blob/4a49170ea46c4bae244a32b7e460534b56ccf02c/ui/src/sandbox.rs#L398)? Only issue I found is that that function doesn't have a parameter which would allow it to determine if it runs on nightly or not.

**Comment by shepmaster** [comment]
> For implementation, I think it might be enough to add the flag here? Only issue I found is that that function doesn't have a parameter which would allow it to determine if it runs on nightly or not.

I think you are right. Would you care to take this enhancement on?

I think just adding the channel as an argument to that function is fine. And some point we will need to step back and re-evaluate how all that stuff interacts...
