### ISSUE TITLE
Redirect from HTTP site to HTTPS site appends an additional slash to the URL which breaks share links

### ISSUE THREAD

**Issue by aleksijuvani** [integer32llc/rust-playground#418]
Steps to reproduce:

1. Visit "play.rust-lang.org" via the address bar in Firefox (resolves to "http://play.rust-lang.org/")
2. Browser is redirected to HTTPS site "https://play.rust-lang.org//" (notice the two slashes at the end)
3. Copying a share link will result in a link with two slashes, e.g. "https://play.rust-lang.org//?version=stable&mode=debug&edition=2015&gist=f50a61e2f0f4d73812607fbef4cff774"
4. Visiting the link with two slashes will not open the shared code, but will instead open the default "hello world" example
5. Manually removing the second slash from the link works: "https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=f50a61e2f0f4d73812607fbef4cff774"

**Comment by shepmaster** [comment]
Thanks!
