### ISSUE TITLE
Code lost when closing a tab and restoring it

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#426]
Usually, when I close a tab and then hit Ctrl-Shift-T to reopen the last closed tab, it comes back with the form content still intact. This also means I can restart my browser, even my system, without losing form content.

However, for the playground, when I do that (in Firefox), it always comes back with the example code.  That is somewhat unexpected data loss.

**Comment by shepmaster** [comment]
I'm going to need deeper reproduction steps. The playground has persisted every keystroke to the browser's LocalStorage since day 1. It's even [documented in the help](https://play.integer32.com/help#features-persistence)

**Comment by shepmaster** [comment]
Here's [a zipped movie](https://github.com/integer32llc/rust-playground/files/2558621/repro.mov.zip)
 (sigh) of it working.

**Comment by lqd** [comment]
(persistence works for me as well)

**Comment by RalfJung** [comment]
Reproduction steps are quite simple: Edit the code, close tab, reopen tab. Code is reset to default.

However, now that you mention LocalStorage, this might be related to my privacy settings. I will try adding the playground to the whitelist for cross-session cookies, maybe that helps.

**Comment by RalfJung** [comment]
Ah, yes, that did the trick.

However, playground still behaves very different from other sites once multiple tabs are involved:

* Open playground twice.
* Type different things in the two tabs.
* Close them both.
* Restore them both.

Now both tabs have the same content; one of the two is lost. Other sites are usually able to properly restore per-tab data (e.g. comment text in GitHub is restored per-tab).

I usually have plenty of tabs open, so this will happen regularly during normal use.

**Comment by shepmaster** [comment]
> very different from other sites once multiple tabs are involved

As [stated in the help](https://play.integer32.com/help#features-persistence):

> Local storage is a singleton resource, so if you use multiple windows, only the most recently saved code will be persisted.

If you can point us to another website that has a similar rich editor and per-tab data, it's possible we can steal how they work. However, making such a decision would be a "breaking change", as then opening a new playground would no longer restore the previous code.

Note that the playground has always used local storage, just like [the playpen before it](https://github.com/rust-lang/rust-playpen/blob/1d0975ed13716bbc1c242fdbdf75dc4c6e42f8d3/static/web.js#L664-L675)

**Comment by RalfJung** [comment]
> opening a new playground would no longer restore the previous code.

I would actually welcome that. I like tabs restoring their content when I restart my browser. I do not like the fact that every time I come to the playground for a new example, I first have to delete my last example and write `fn main() {}` again. I was happy this stopped some time ago, now I understand what was because I changed some privacy settings (or because Firefox started treating LocalStorage more like cookies).

Though this got much less of a problem now that I can just empty the entire tetx box and it'll switch to `Build` instead of `Run` automatically.

**Comment by RalfJung** [comment]
> If you can point us to another website that has a similar rich editor and per-tab data

I have no idea how to evaluate "similar rich editor", but https://godbolt.org/ does restore per-tab data properly, and it at least has syntax highlighting.

**Comment by shepmaster** [comment]
I'm going to start storing the code in *session storage* in addition to local storage. This will allow the code to be restored on a tab reopen. A new tab will continue to restore the last-entered code of any window.

I need to decide if a few other things should be saved (build mode, mostly, although I should re-enable backtrace URL support separately)

**Comment by shepmaster** [comment]
This will benefit users of the playground<sup>1</sup> who have multiple tabs open, we love them!

---

1. Beyond those that have equipped their tin-foil hats and are preventing [hackerman](https://i.kym-cdn.com/entries/icons/original/000/021/807/4d7.png) from stealing their precious Miri test cases. 😈

**Comment by shepmaster** [comment]
The playground has strong caching. You need to either wait 24 hours or shift-reload the page.

**Comment by RalfJung** [comment]
Confirmed. :) :heart:
