### ISSUE TITLE
miri does not use the correct edition

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#429]
In [this example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5634a19882ab427ff02dac3fcb675431), "Build" works fine because we selected the 2018 edition, but running it in miri seems to use the 2015 edition.

Is there something miri should change here, or does the playground have to inform miri somehow?

**Comment by RalfJung** [comment]
clippy has the same problem, it also has the borrow checker complain in the above example.

rustfmt does not care, likely because it does not do borrow checking.

**Comment by shepmaster** [comment]
As far as you know, setting `edition = ...` in Cargo.toml is all that Miri needs?

**Comment by RalfJung** [comment]
I have no idea. `cargo miri` is just a small shim that calls `miri`, and it seems possible that it has to add the `--edition` flag itself.

**Comment by shepmaster** [comment]
The most likely place to start poking on the playground side is to get this bit of code (or similar) to trigger:

https://github.com/integer32llc/rust-playground/blob/a7148c804cb2d94f062b44b4bc3e516bd6922a7c/ui/src/sandbox.rs#L473-L475

This touches one of the objectively *worst* pieces of the playground because setting up the Docker environment is a big ol' ball of wax.

**Comment by shepmaster** [comment]
I think that the playground will have some work to do as well in a very similar location. For example, you can't run Clippy on input without a `main`, presumably because I've never passed that information down to the right level.

**Comment by RalfJung** [comment]
A local test indicates that `cargo miri` is doing this correctly.

**Comment by RalfJung** [comment]
Uh actually I may have spoken too fast. I see no output at all any more when I enable the new edition. Investigating.^^

**Comment by RalfJung** [comment]
Argh I just forgot to get libstd with all the MIR.^^ Yes, editions are properly supported by cargo miri, so I think playground is the only missing piece.

**Comment by RalfJung** [comment]
Now that the 2018 edition is the default on the playground, this is even more noticeable.
