### ISSUE TITLE
Playground fails to load - session storage value for "redux" is null

### ISSUE THREAD

**Issue by Arnavion** [integer32llc/rust-playground#433]
Page is blank. Console shows this error:

```
8cc65fe859fbd039fa13.js:1 Uncaught TypeError: Cannot read property 'version' of null
    at deserialize (8cc65fe859fbd039fa13.js:1)
    at 8cc65fe859fbd039fa13.js:1
    at 8cc65fe859fbd039fa13.js:1
    at 2db6ccab5336953f0406.js:1
    at u (2db6ccab5336953f0406.js:1)
    at Module.334 (8cc65fe859fbd039fa13.js:1)
    at i (8cc65fe859fbd039fa13.js:1)
    at Object.176 (8cc65fe859fbd039fa13.js:1)
    at i (8cc65fe859fbd039fa13.js:1)
    at n (8cc65fe859fbd039fa13.js:1)
deserialize @ 8cc65fe859fbd039fa13.js:1
(anonymous) @ 8cc65fe859fbd039fa13.js:1
(anonymous) @ 8cc65fe859fbd039fa13.js:1
(anonymous) @ 2db6ccab5336953f0406.js:1
u @ 2db6ccab5336953f0406.js:1
334 @ 8cc65fe859fbd039fa13.js:1
i @ 8cc65fe859fbd039fa13.js:1
176 @ 8cc65fe859fbd039fa13.js:1
i @ 8cc65fe859fbd039fa13.js:1
n @ 8cc65fe859fbd039fa13.js:1
(anonymous) @ 8cc65fe859fbd039fa13.js:1
(anonymous) @ 8cc65fe859fbd039fa13.js:1
```

Specifically, at this line:

https://github.com/integer32llc/rust-playground/blob/master/ui/frontend/local_storage.ts#L32

the deserialized `parseState` value is `null` because the string given to `JSON.parse` is `"null"`

The value comes from the caller here:

https://github.com/integer32llc/rust-playground/blob/master/ui/frontend/storage.ts#L45

where the `storage.getItem()` call added in https://github.com/integer32llc/rust-playground/commit/f2f84d172df07ede11b8a0f6f105c0bf13d52940 returns `"null"`. The `key` is `"redux"` This is in fact the only key in the session storage.

```
$ window.sessionStorage
> Storage {redux: "null", length: 1}
```

---

The `"null"` stored in session storage comes from the try-catch here:

https://github.com/integer32llc/rust-playground/blob/master/ui/frontend/storage.ts#L36-L37

The first time the page is loaded and the key doesn't exist, `storage.getItem()` returns `null`, which the `storage.setItem` in the next line stringifies and stores as `"null"`. The next `storage.getItem()` will then load the same `"null"` back.

Since the `setItem` was explicitly added there to test for being able to set session storage in https://github.com/integer32llc/rust-playground/commit/f2f84d172df07ede11b8a0f6f105c0bf13d52940, perhaps `deserialize` should handle both `undefined` and `JSON.parse()` returning `null` to mean the same.

**Comment by shepmaster** [comment]
Spot on analysis! I... wish I had read my issues before doing my own investigation 😊 

> which the `storage.setItem` in the next line stringifies

This was my key mistake. That's behavior I didn't want and didn't expect. 

> perhaps `deserialize` should handle both `undefined` and `JSON.parse()` returning `null` to mean the same.

I agree. Done in #434 

Thank you for providing such thorough analysis!

**Comment by shepmaster** [comment]
The fix has been pushed; because the playground has stronger caching, you will either need to wait 24h or force a reload of the page.
