### ISSUE TITLE
Rustfmt has lost its version string

### ISSUE THREAD

**Issue by lqd** [integer32llc/rust-playground#437]
It appears the rustfmt string isn't showing anymore.

![image](https://user-images.githubusercontent.com/247183/49298830-983e8d80-f4be-11e8-8a4b-4944c92b070c.png).

It doesn't look like a client-side issue as the meta information is [just empty](https://play.rust-lang.org/meta/version/rustfmt).

I think there was some renaming in the rustup component, so some things did change with rustfmt recently.

**Comment by shepmaster** [comment]
```
$ cargo +nightly fmt --version
$ echo $?
0
```

Seems like an upstream issue.

**Comment by shepmaster** [comment]
https://github.com/rust-lang/rustfmt/issues/3214

**Comment by lqd** [comment]
oh good spot, I had tried `rustfmt --version` which works, so this should fix itself by the next release (maybe the next nightly, it's not clear to me when rustfmt releases are propagated through rustup)

**Comment by shepmaster** [comment]
> when rustfmt releases are propagated through rustup

I *believe* that a PR has to be submitted to rust-lang/rust.

**Comment by CYBAI** [comment]
I found the rustfmt version is still empty and using `rustfmt --version` works. Would you think we should use `rustfmt --version` to avoid it's missing from nightly release 👀?

<img width="389" alt="empty rustfmt version" src="https://user-images.githubusercontent.com/6782666/56452643-6abf8700-636e-11e9-96f2-bbb18a9bfc58.png">

**Comment by shepmaster** [comment]
I’d rather we re-report this upstream to see if it’s deliberate.

**Comment by shepmaster** [comment]
And it appears fixed again:

![image](https://user-images.githubusercontent.com/174509/56457270-156f7f80-6346-11e9-8cc0-009255be0ff8.png)
