### ISSUE TITLE
Consider using monaco-editor in place of ace

### ISSUE THREAD

**Issue by KSXGitHub** [integer32llc/rust-playground#450]
[Monaco](https://microsoft.github.io/monaco-editor/) is an embedded editor that is used by VSCode and [TypeScript playground](https://www.typescriptlang.org/play/).

## Why?

* It has more features out-of-the-box (such as right-click context menu, command palette <kbd>F1</kbd>, etc.).
* It is extensible (you can add themes, IntelliSense and whatnot).
* In theory, Rust Language Server should work well with Monaco as it does in VS Code. (related to https://github.com/integer32llc/rust-playground/issues/357)

**Comment by shepmaster** [comment]
> * It has more features out-of-the-box (such as right-click context menu, command palette F1, etc.).

What purpose do these features serve? For example, what needs to go into the hypothetical context menu or command palette? How would these changes help the users of the playground?

> * It is extensible (you can add themes, IntelliSense and whatnot).

Again, what purpose do these features serve? Who can add themes? If it's the playground implementers, that's already possible today. Who *wants* to add themes?

IntelliSense is a broad category of functionality. The current playground already has a form of autocomplete for crates. What aspects of IntelliSense do people want? What will provide the data for that?

> * In theory, Rust Language Server should work well with Monaco as it does in VS Code

I'm pretty sure that there's *several* jumps to get from point A to point B here. Electron has access to many things that a browser does not.

**Comment by shepmaster** [comment]
I'm not *against* such a change, but I don't see any value in it at this moment. This feels like a "rewrite it in Rust" type of issue.

**Comment by KSXGitHub** [comment]
> What purpose do these features serve? For example, what needs to go into the hypothetical context menu or command palette? How would these changes help the users of the playground?

Context menu allows extending functionality without cluttering UI.

> What aspects of IntelliSense do people want?

All of RLS + VS Code:
  * Pop-up that shows type annotation and documentation when user move their mouse cursor over a name.
  * Jump to definition, peek definition.
  * Symbols.
  * Autocompletion.
  * etc.

> What will provide the data for that?

> Electron has access to many things that a browser does not.

The same source the compiles and runs the code (which I'm pretty sure isn't the browser).

> This feels like a "rewrite it in Rust" type of issue.

Unlike "rewrite it in Rust" which is essentially just refactoring into another language, this change changes functionality and user experience.
