### ISSUE TITLE
Copy-Paste not working in iOS (iPhone)

### ISSUE THREAD

**Issue by rerime** [integer32llc/rust-playground#451]
Can't paste my code from Safari, iOS. Long tap on screen not working.
How to reproduce: just try paste anything at playground from iPhone.

**Comment by shepmaster** [comment]
This is likely due to the fact that the Ace editor doesn't fully support mobile. Can you try switching to the simple editor:

![image](https://user-images.githubusercontent.com/174509/50849617-8e256f80-1345-11e9-9d31-a63cafe374aa.png)

**Comment by rerime** [comment]
It works! Thx 💪😊
