### ISSUE TITLE
Linting code with Clippy does not properly account for the selected Rust edition

### ISSUE THREAD

**Issue by hellow554** [integer32llc/rust-playground#456]
# What I did

Ran Clippy on the following Rust 2018 code:

```rust
use base64::STANDARD; // 0.10.0

fn main() {
    println!("{:?}", STANDARD);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3d9ce7f5687f2e278e66c6cfe837b5f3))

# What happened

Clippy complains about a missing external crate:

```
error[E0432]: unresolved import `base64`
 --> src/main.rs:1:5
  |
1 | use base64::STANDARD; // 0.10.0
  |     ^^^^^^ maybe a missing `extern crate base64;`?
``` 

# What I expected to happen

I expected the code to be validly parsed and Clippy warnings to be printed (if any).

# Additional information

The  code compiles/runs fine when using "Run".

**Comment by CYBAI** [comment]
I can run the playground without error with `edition 2018`.

**Comment by hellow554** [comment]
It is not about running the code, but using clippy (!).

**Comment by shepmaster** [comment]
Without more specific dates, the only thing I can think of would be a9e090f6ebd4c76ab11f6ae5db8d0badee8097f6, but if anything, that should make Clippy work with edition 2018.

**Comment by hellow554** [comment]
I think it's https://github.com/integer32llc/rust-playground/commit/a9e090f6ebd4c76ab11f6ae5db8d0badee8097f6 who mixed it up, because https://github.com/integer32llc/rust-playground/blob/master/compiler/base/modify-cargo-toml/Cargo.toml has not the edition key in it.

**Comment by hellow554** [comment]
I think one should do the same with clippy as Ralf Jung did with miri (https://github.com/integer32llc/rust-playground/commit/0507fdb83fdb969fa86d421b9f8a88135490bbd6 and https://github.com/integer32llc/rust-playground/commit/5b849b426cc7d03f80888ce11d06b872dfc7cda5) and add the edition parameter to clippy request as well.

**Comment by shepmaster** [comment]
That's certainly believable, and what I'd suggest, but it wouldn't explain how you were able to run clippy with Rust 2018 before. Without **both** the change to set the environment variable and the change to the entrypoint, the edition won't be set inside the container.

**Comment by hellow554** [comment]
Maybe it never worked in the first place and I just assumed it worked, because, well.. it worked ^^
It could be, that I never ran into the need of the 2018 edition and I just found out by accident. 

So I guess it has to be implemented ^^

**Comment by tommyshem** [comment]
Tested below code and it works with 2015, 2018 compiler and clippy.
```rust
extern crate base64; // 0.10.0
use base64::{STANDARD};
fn main() {
    println!("{:?}", STANDARD);
}
```
See base64 crate website with example on it https://crates.io/crates/base64

**Comment by shepmaster** [comment]
@tommyshem I don't understand the relevance of that code to this issue. Perhaps you misunderstood the title original comment. I will edit it.

**Comment by tommyshem** [comment]
Yes you are right a misunderstood, as I thought you could not get the code compiling on both rust versions and clippy.  As rust version 2018 does not need extern crate.
Sorry for any confusion.
