### ISSUE TITLE
Rustfmt should run under the selected edition mode

### ISSUE THREAD

**Issue by scottmcm** [integer32llc/rust-playground#464]
I was looking at https://github.com/rust-lang/rust/issues/58491, and tried to format this working code: https://play.rust-lang.org/?version=nightly&edition=2018&gist=7e6d977543fff0d7b0b2da8c864f1c69

RustFmt, however, gave the parsing error that gets in the 2015 edition.  I'm guessing that means the appropriate edition flags aren't being passed for tools?

**Comment by shepmaster** [comment]
Huh, I thought for sure that rustfmt didn't care about the edition. We've addressed this for Miri in #454 and Clippy in #461. Guess I should have actually tested...
