### ISSUE TITLE
Raw identifiers sometimes highlighted as keyword

### ISSUE THREAD

**Issue by chertl** [integer32llc/rust-playground#466]
The syntax highlighting does not seem to handle [raw identifiers (r#)](https://doc.rust-lang.org/book/appendix-01-keywords.html#raw-identifiers).

For example, declaring a variable named "unsafe" will display `unsafe` in bold - even though it is not used as a keyword:

**let** r#**unsafe**;

Here, `unsafe` should be displayed like any other variable name:

**let** name;

**Comment by shepmaster** [comment]
Pretty sure this is going to need to be a PR to https://github.com/ajaxorg/ace. @nightwing has been super helpful in helping us make changes to Ace in previous cases, they might help point out where to fix it.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3896 should fix this, Could you please test on https://raw.githack.com/ajaxorg/ace/rust-raw-identifier/kitchen-sink.html?doc=Rust to see if it works the way you expect?

**Comment by chertl** [comment]
Thanks for the fast response! This fix correctly handles the case :)

**Comment by shepmaster** [comment]
I'm going to reopen this to track actually upgrading to the next version of Ace. Thank you so much @nightwing !

**Comment by shepmaster** [comment]
Fix [released in ace 1.4.3](https://github.com/ajaxorg/ace/compare/v1.4.2...v1.4.3); now waiting for [brace](https://github.com/thlorenz/brace) to incorporate it.

**Comment by shepmaster** [comment]
Also watching with interest https://github.com/securingsincity/react-ace/issues/512; on the off chance we could skip brace altogether.
