### ISSUE TITLE
Docker mount denied on macOS

### ISSUE THREAD

**Issue by CYBAI** [integer32llc/rust-playground#480]
While trying to run `rust-playground` locally, I can build the compiler docker images successfully and also launch `ui` folder successfully. However, if I tried to `run`, `build` or `rustfmt` (any commands need docker) in my localhost, I will get following error

```
docker: Error response from daemon: Mounts denied: 
The paths /var/folders/dx/l5pn75zx5v9_cwstvgwc5qyc0000gn/T/playground.6gEHdGUM6XPU/output and /var/folders/dx/l5pn75zx5v9_cwstvgwc5qyc0000gn/T/playground.6gEHdGUM6XPU/input.rs
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
time="2019-04-19T13:36:22+09:00" level=error msg="error waiting for container: context canceled"
```

I tried to follow the instruction `Docker -> Preferences... -> File Sharing` to set the path but I can't add it because the `/private` path already includes the `/var/folders` that `/private` is default paths for macOS.

After doing some search, I found [this SO answer](https://stackoverflow.com/a/45123074/1863619) looks related but still not figure out how to fix it yet.

**Comment by shepmaster** [comment]
I use docker-machine, not Docker for Mac, but I had similar problems. I need to set the `TMPDIR` environment variable to a location where Docker can share files from. 

For example, I have `~/Projects/integer32/playground/tmp` and I use `TMPDIR=~/Projects/integer32/playground/tmp cargo run`.

**Comment by CYBAI** [comment]
@shepmaster Thank you so much! It works for me as well! I'm using Docker for Mac! Then, let me close this issue, thanks! 🙇
