### ISSUE TITLE
Updating the mdBook endpoint

### ISSUE THREAD

**Issue by ehuss** [integer32llc/rust-playground#486]
mdBook currently uses the JSON API from the `/evaluate.json` endpoint to run examples inline.  Unfortunately that endpoint doesn't support some of the features from the newer `/execute` endpoint.  I briefly spoke with @shepmaster about this, and he said it would be best not to change to the `/execute` endpoint.  So I'd like to check to see if a PR to add the some fields to the older endpoint be OK?  In particular, the `edition` field is the most important, but the `test` field would also be nice.  It [looks like](https://github.com/integer32llc/rust-playground/blob/5c3ee96373426204dc034e9b36c784ed94cb1623/ui/src/main.rs#L845) it should be relatively easy to add.

**Comment by shepmaster** [comment]
Yes, I think adding parameters for edition and test to `evaluate.json` should be straight forward and is certainly welcome.

The only trick is that you'll need to ensure backwards compatibility by handling missing parameters as the current default values.
