### ISSUE TITLE
Undoing edits removes seemingly random characters

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#496]
Starting from a blank editor, type `fn main() {`, then hit enter - you will be automatically indented 4 spaces in and a closing curly brace `}` will be added below. Then type anything, and hit ctrl-Z. The text you typed will have random characters removed and the cursor will be moved to the very bottom right, after the `}`.

![ezgif-2-2ea6a90aecc2](https://user-images.githubusercontent.com/6751033/58759455-48399580-84f8-11e9-9ccb-78b8de1986d5.gif)

/cc @mikeyhew (originally from https://github.com/integer32llc/rust-playground/issues/494#issuecomment-498015199)

**Comment by nightwing** [comment]
It seems like debounce still breaks the undo selections as it still sets editor value to the older value while editing. I think it may be better to use silenceOnChange.current to exit from useEditorProp as well without debouncing.

```diff
--- a/ui/frontend/AdvancedEditor.tsx
+++ b/ui/frontend/AdvancedEditor.tsx
@@ -134,7 +134,9 @@ const AdvancedEditor: React.SFC<AdvancedEditorProps> = props => {
   useEditorProp(props.onEditCode, (editor, onEditCode) => {
     const listener = editor.on<true>('change', _delta => {
       if (!silenceOnChange.current) {
+        silenceOnChange.current = true;
         onEditCode(editor.getValue());
+        silenceOnChange.current = false;
       }
     });
 
@@ -144,6 +146,9 @@ const AdvancedEditor: React.SFC<AdvancedEditorProps> = props => {
   });
 
   useEditorProp(props.code, (editor, code) => {
+    if (silenceOnChange.current) {
+      return;
+    }
     if (editor.getValue() !== code) {
       silenceOnChange.current = true;
       const currentSelection = editor.selection.toJSON();
```

**Comment by shepmaster** [comment]
> It seems like debounce still breaks the undo selections

I'm not following what you mean; if I type in some values and undo them, it appears to do what I expect:

![undo](https://user-images.githubusercontent.com/174509/58763805-de3be300-852d-11e9-9b0c-6c11464e5d8e.gif)

**Comment by shepmaster** [comment]
Thank you so much for your assistance, @nightwing, and sorry to ping you on these issues which are clearly my own fault 😊

**Comment by nightwing** [comment]
That's our fault for not having better documentation :)

![gif](https://user-images.githubusercontent.com/341801/58764101-5b8a4680-8574-11e9-9573-fc537891a6ad.gif)
When I type quickly  several characters appear after the cursor, and when undoing the whole text in the editor is selected at the times when editor.setValue was called

**Comment by shepmaster** [comment]
> type quickly several characters appear after the cursor

Ah yes, I also saw this. I assume it's because the Ace events cross a RAF boundary and so we still get events "too late".

I think I'd like to leave the debouncing as it reduces spurious updates, so I tried:

```diff
diff --git a/ui/frontend/AdvancedEditor.tsx b/ui/frontend/AdvancedEditor.tsx
index 54149ab..cfe2149 100644
--- a/ui/frontend/AdvancedEditor.tsx
+++ b/ui/frontend/AdvancedEditor.tsx
@@ -145,12 +145,20 @@ const AdvancedEditor: React.SFC<AdvancedEditorProps> = props => {
     editor.completers = [buildCrateAutocompleter(autocompleteOnUse, crates)];
   });
 
+  const guarded = f => {
+    if (!silenceOnChange.current) {
+      silenceOnChange.current = true;
+      f();
+      silenceOnChange.current = false;
+    }
+  };
+
   const onEditCodeDebounced = useRafDebouncedFunction(props.onEditCode);
   useEditorProp(onEditCodeDebounced, (editor, onEditCode) => {
     const listener = editor.on<true>('change', _delta => {
-      if (!silenceOnChange.current) {
+      guarded(() => {
         onEditCode(editor.getValue());
-      }
+      });
     });
 
     return () => {
@@ -159,13 +167,14 @@ const AdvancedEditor: React.SFC<AdvancedEditorProps> = props => {
   });
 
   useEditorProp(props.code, (editor, code) => {
-    if (editor.getValue() !== code) {
-      silenceOnChange.current = true;
-      const currentSelection = editor.selection.toJSON();
-      editor.setValue(code);
-      editor.selection.fromJSON(currentSelection);
-      silenceOnChange.current = false;
-    }
+    guarded(() => {
+      if (editor.getValue() !== code) {
+        const currentSelection = editor.selection.toJSON();
+        console.log('setting...');
+        editor.setValue(code);
+        editor.selection.fromJSON(currentSelection);
+      }
+    });
   });
 
   useEditorProp(props.theme, (editor, theme) => {
```

However, the "extra characters at the end" problem still exists; did I mis-interpret your suggestion?

**Comment by shepmaster** [comment]
Hmm, perhaps I need to have two separate flags so they don't collide with each other...

**Comment by nightwing** [comment]
If one of the calls to guarded is debounced, then `silenceOnChange.current = true` set from the other will not have any effect because by the time the function is called it will be set back to false.

**Comment by shepmaster** [comment]
> one of the calls to guarded is debounced

Yeah, I was worried about that, but the function itself (`onEditCodeDebounced` / `onEditCode`) is debounced, so `guarded` was called outside of that.

**Comment by shepmaster** [comment]
but, doing the exact thing you suggested does work, so I guess I need to turn up my brainpower or write out some timing diagrams...

**Comment by shepmaster** [comment]
I think I understand now: the instance variable technique (here provided by React's `useRef`) requires that the `getValue` and `setValue` be called synchronously. This is fine when we set the value because Ace is going to synchronously emit one or more change events in response to `setValue`.

However, I don't think it's good to rely on React / Redux / etc. doing the inverse: synchronously performing the `setValue` in response to a `change`. I believe that there's ongoing work to make React actively work less synchronously (fibers).

In absence of that, I see two main avenues:

1. Ace could somehow provide "chunkier" events than `change`. This magic event would be fired after the user-initiated change and any editor-initiated changes. This would nicely accomplish my goal.
  - Variations on this would include polling Ace during the `change` event to ask if any further events are known to be pending.
1. Somehow track through our state that the most recent change came from Ace itself and not some other mechanism and prevent calling `setValue` in that case.

Obviously, I prefer the former as it's less work I'd have to do 😈. It also seems like it would help more people as I'm sure that there are other cases where people are using Ace in a similar fashion.

The latter is more achievable by our own amount of work, and might be worth doing as a stop-gap to start with.

**Comment by nightwing** [comment]
What is the downside of keeping both calls synchronous? as in https://github.com/integer32llc/rust-playground/issues/496#issuecomment-498042452

There is already a chunkier event `input`, which is fired after a timeout, but to use that the logic of the code prop handler needs to be changed, but i do not quite understand what it does now.

**Comment by nightwing** [comment]
```js
  var lastValue: string, lastProp: string
  useEditorProp(props.onEditCode, (editor, onEditCode) => {
    const listener = editor.on('input', () => {
        lastValue = editor.getValue();
        if (lastValue == lastProp) {
            return lastProp = null;
        }
        onEditCode(lastValue);
    });

    return () => {
      editor.off('input', listener);
    };
  });

  useEditorProp(props.code, (editor, code) => {
    if (code == lastValue) {
        return lastValue = null;;
    }
    var value = editor.getValue()

    if (value !== code) {
      
      lastProp = code;
      const currentSelection = editor.selection.toJSON();
      editor.setValue(code);
      editor.selection.fromJSON(currentSelection);
    }
  });
```
this also seems to work

**Comment by shepmaster** [comment]
> What is the downside of keeping both calls synchronous

Pragmatically, there is no downside *right now*. As far as I know<sup>1</sup>, all the state updates done by Redux are synchronous and there's no plan to change that core aspect<sup>2</sup>. However, how data is passed through the React tree is subject to change (via [Concurrent React](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-q2-2019-the-one-with-concurrent-mode)). As I understand it, this would allow the data passed back to my component (and thus Ace) to happen asynchronously, defeating the synchronous requirements of the instance variable. 

---

1 — And I don't claim to know that much.

2 — Although the most common store enhancers *add* asynchronous abilities.

**Comment by shepmaster** [comment]
What do you think about this idea:

Every time this React component calls the callback, we add the data to a list. Whenever the prop changes, we check the head of that list. If it matches, we know that we generated this event, so we can discard it.

Something like this seems to work:

```diff
diff --git a/ui/frontend/AdvancedEditor.tsx b/ui/frontend/AdvancedEditor.tsx
index 54149ab..af32bc6 100644
--- a/ui/frontend/AdvancedEditor.tsx
+++ b/ui/frontend/AdvancedEditor.tsx
@@ -37,7 +37,7 @@ const buildCrateAutocompleter = (autocompleteOnUse: boolean, crates: Crate[]): A
   },
 });
 
-function useRafDebouncedFunction<A extends any[]>(fn: (...args: A) => void) {
+function useRafDebouncedFunction<A extends any[]>(fn: (...args: A) => void, onCall?: (...args: A) => void) {
   const timeout = useRef<number>();
 
   return useCallback((...args: A): void => {
@@ -47,8 +47,9 @@ function useRafDebouncedFunction<A extends any[]>(fn: (...args: A) => void) {
 
     timeout.current = window.requestAnimationFrame(() => {
       fn(...args);
+      if (onCall) { onCall(...args); }
     });
-  }, [fn, timeout]);
+  }, [fn, onCall, timeout]);
 }
 
 interface AdvancedEditorProps {
@@ -70,7 +71,6 @@ interface AdvancedEditorProps {
 const AdvancedEditor: React.SFC<AdvancedEditorProps> = props => {
   const [editor, setEditor] = useState<AceEditor>(null);
   const child = useRef<HTMLDivElement>(null);
-  const silenceOnChange = useRef(false);
 
   useEffect(() => {
     if (!child.current) { return; }
@@ -145,12 +145,37 @@ const AdvancedEditor: React.SFC<AdvancedEditorProps> = props => {
     editor.completers = [buildCrateAutocompleter(autocompleteOnUse, crates)];
   });
 
-  const onEditCodeDebounced = useRafDebouncedFunction(props.onEditCode);
+
+  // Both Ace and the playground want to be the One True Owner of
+  // the textual content. This can cause issues because the Redux
+  // store will attempt to change Ace in response to changes
+  // *originating* from Ace. In addition, Ace can generate multiple
+  // `change` events in response to what looks like a single
+  // action. This includes:
+  //
+  // - Auto-indenting after pressing return
+  // - Invoking undo
+  // - Multi-cursor editing
+  //
+  // To avoid issues
+  //
+  // 1. We throttle outgoing events to once per animation frame,
+  //    only sending the most recent update.
+  //
+  // 2. We keep a log of all outgoing events. If we see that event
+  //    come back next via the`code` property, we ignore it.
+  //
+  // 3. We check to see if the `code` property is already what Ace has
+  //    and avoid pointless updates.
+  const previouslyNotified = useRef([]);
+  const onEditCodeDebounced = useRafDebouncedFunction(
+    props.onEditCode,
+    useCallback((code) => previouslyNotified.current.push(code), [previouslyNotified]),
+  );
+
   useEditorProp(onEditCodeDebounced, (editor, onEditCode) => {
     const listener = editor.on<true>('change', _delta => {
-      if (!silenceOnChange.current) {
-        onEditCode(editor.getValue());
-      }
+      onEditCode(editor.getValue());
     });
 
     return () => {
@@ -159,13 +184,23 @@ const AdvancedEditor: React.SFC<AdvancedEditorProps> = props => {
   });
 
   useEditorProp(props.code, (editor, code) => {
-    if (editor.getValue() !== code) {
-      silenceOnChange.current = true;
-      const currentSelection = editor.selection.toJSON();
-      editor.setValue(code);
-      editor.selection.fromJSON(currentSelection);
-      silenceOnChange.current = false;
+    // Is this prop update the result of our own `change` event?
+    const last = previouslyNotified.current.shift();
+    if (code === last) {
+      return;
     }
+
+    // It wasn't; discard any remaining events to resync
+    previouslyNotified.current = [];
+
+    // Avoid spuriously resetting the text
+    if (editor.getValue() === code) {
+      return;
+    }
+
+    const currentSelection = editor.selection.toJSON();
+    editor.setValue(code);
+    editor.selection.fromJSON(currentSelection);
   });
 
   useEditorProp(props.theme, (editor, theme) => {
```

**Comment by nightwing** [comment]
This indeed works, it seems like there should be a simpler method to achieve this, but unfortunately i don't know react and redux well enough.

**Comment by shepmaster** [comment]
> i don't know react and redux well enough.

Again, I'm not sure I do either. :-) I know a lot of the ceremony involved is mostly around avoiding creating new objects when the inputs haven't actually changed, which is used to prevent needless re-rendering when passing those objects down to child components. A lot of that isn't needed here because Ace itself *isn't* a React component, but that's me being overly cautious and establishing good habits for *other* React components.
