### ISSUE TITLE
When I type quickly, several characters appear after the cursor. When undoing, the whole text in the editor is selected.

### ISSUE THREAD

**Issue by Stargateur** [integer32llc/rust-playground#498]
Simply a "clean" issue for https://github.com/integer32llc/rust-playground/issues/496#issuecomment-498045478

![demo](https://user-images.githubusercontent.com/341801/58764101-5b8a4680-8574-11e9-9573-fc537891a6ad.gif)

As the original issue is close but this bug still haven't be fix.

**Comment by shepmaster** [comment]
Honest question: are you typing that fast or banging on the keyboard? I can only reproduce it by mashing keys.

**Comment by Stargateur** [comment]
I just tried to reproduce the first bug to see if it was gone, so I just smashed the keyboard, the cursor moving to the end was gone but this new one appear ;) So I take a look at issues and saw that it have been report but inside the other side.

I'm not sure I can trigger it in a fair use, but still a bug ^^

**Comment by shepmaster** [comment]
I think I actually have triggered this a few times, but it looks just like a strange kind of typo. People are probably actually triggering this in the wild.
