### ISSUE TITLE
does not support  #![feature(main)]

### ISSUE THREAD

**Issue by matthiaskrgr** [integer32llc/rust-playground#503]
````rust
#![feature(main)]

#[main]
fn a() {
    println!("hi");
}
````
When I run it locally, I get a "hi", but playground says

````
   Compiling playground v0.0.1 (/playground)
warning: function is never used: `a`
 --> src/lib.rs:6:1
  |
6 | fn a() {
  | ^^^^^^
  |
  = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1.43s

Warnings

No main function was detected, so your code was compiled
but not run. If you'd like to execute your code, please
add a main function.
````

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7ff692f07c7c3562df289936dbc97eda

**Comment by shepmaster** [comment]
Yes, the automatic detection of whether to run `cargo run` / `cargo build` / `cargo test` is based on a simple regex match. You don't have `fn main()` so the regex isn't triggered. You need to expressly request to run the code:

![image](https://user-images.githubusercontent.com/174509/59435525-d09f1c80-8dbb-11e9-91bf-99d30579add9.png)

You'll note that the button says "build" not "run" before you do this.

**Comment by matthiaskrgr** [comment]
Thanks for clarifying! :+1:
