### ISSUE TITLE
Even better if we link compile errors to details

### ISSUE THREAD

**Issue by gilescope** [integer32llc/rust-playground#506]
The excellent clion hyperlinks the "--explain E0225" error message to https://doc.rust-lang.org/error-index.html#E0225

Playground is great and would be even better if it also hyperlinked to the detailed explanations.

**Comment by shepmaster** [comment]
We [already link to error details](https://github.com/integer32llc/rust-playground/blob/673ffa7b3326a9e444db9c52aaf378759f9b62d3/ui/frontend/highlighting.ts#L35-L41). Perhaps you could include a screenshot of what you mean?

**Comment by shepmaster** [comment]
I'm going to close this as it's unclear what the request is.
