### ISSUE TITLE
Editor line shift when inserting emoji

### ISSUE THREAD

**Issue by hellow554** [integer32llc/rust-playground#509]
As you can see, if one adds an emoji, the line gets slightly shifted downwards and therefore interferes with the next line

![grafik](https://user-images.githubusercontent.com/921462/60647177-62d79500-9e3d-11e9-8173-6c05a363f580.png)

![grafik](https://user-images.githubusercontent.com/921462/60647195-6bc86680-9e3d-11e9-8481-410c1244110a.png)

**Comment by shepmaster** [comment]
This is apparently a problem with Ace, as the demo [on their website](https://ace.c9.io/) does the same. Can you check [their repo](https://github.com/ajaxorg/ace) for the root issue or any fixes?

**Comment by nightwing** [comment]
This is indeed a bug in ace. Line text shifts because `line-height: normal` changes based on font. As a temporary workaround until the next version of ace is released you can use

```css
.ace_editor {
    line-height: 1.4;
}
```
or
```js
function onChangeCharacterSize() {
    editor.renderer.scroller.style.lineHeight = editor.renderer.lineHeight + "px"
}
onChangeCharacterSize()
editor.renderer.on("changeCharacterSize", onChangeCharacterSize)
```

**Comment by shepmaster** [comment]
Resolved by upgrading Ace, thank you @nightwing! 😍
