### ISSUE TITLE
Nested `main` causes build error

### ISSUE THREAD

**Issue by joshlf** [integer32llc/rust-playground#511]
The following code snippets seem to cause the playground to interpret the file as a binary (including changing the "build" button to say "run"), but then `rustc` can't find a crate-level `main` function, and so fails compilation:

```rust
mod foo {
    fn main() {}
}
```

```rust
fn foo() {
    fn main() {}
}
```

IMO, only `main` functions at the crate level should cause this behavior.

**Comment by shepmaster** [comment]
Yep!

The automatic selection is done [via simple regexes](https://github.com/integer32llc/rust-playground/blob/5189288f6d67c2d5c11e6153f81a034d058ceefd/ui/frontend/selectors/index.ts#L8-L40). 

If you’d like to fix this, you are welcome to explore an alternate regex or parsing mechanism to make the decision.

In the meantime, you can always override the automatically-selected mode:

![image](https://user-images.githubusercontent.com/174509/60851922-93178e80-a1c3-11e9-9adc-a5134013fdea.png)

**Comment by joshlf** [comment]
Ah, seems like a much more involved fix. Maybe eventually we'll want to wasm-ify the Rust parser, but I think for the time being this is probably a small enough wart that it can be ignored. Thanks for the quick reply!

**Comment by shepmaster** [comment]
> wasm-ify the Rust parser

It’s possible (see #357), but one important thing to continue to preserve is the ability to handle malformed Rust code.
