### ISSUE TITLE
Editor inserts unwanted brackets when typing

### ISSUE THREAD

**Issue by portstrom** [integer32llc/rust-playground#516]
Typing `(` inserts `)` after the caret. Typing `[` inserts `]` after the caret. Typing `{` followed by a line break inserts a line with `}` after the caret. I'd say this is a bug, not a feature. It annoys me all the time, as I have to go and clean up unwanted brackets. The end parentheses `)` sometimes takes care of themselves as typing an end parentheses sometimes overwrites the unsolicited one, but sometimes not, such as when typing a start parenthesis before something that has already been written. I guess I'm expected to select the entire expression I want to surround with parentheses, so that the unsolicited end parenthesis goes at the end of the selection, which is of course not what I do. Knowing this workaround also doesn't help when I only want to insert a lone start parenthesis, which can happen when I want to move a parenthesis from one place to another. The end curly brace `}` doesn't take care of itself at all, requiring erasing entire lines after every block I write. The unwanted end curly braces can also appear outside the viewport when typing at the bottom of the viewport, so I don't see them before I compile and get a surprising syntax error.

**Comment by Nemo157** [comment]
It would be nice if there were an option to disable this, I also find it breaks annoyingly often and just provides extra work to cleanup after it (maybe breaks is the wrong word, maybe it's just incompatible with my coding style since I'm used to working in an editor without it).
