### ISSUE TITLE
Rusqlite present in cookbook, but not on playground.

### ISSUE THREAD

**Issue by thomcc** [integer32llc/rust-playground#517]
The README says crates in the cookbook are present, but rusqlite is not present despite [being in the cookbook](https://rust-lang-nursery.github.io/rust-cookbook/database/sqlite.html#create-a-sqlite-database) (and the following entry about querying).

That said, the policy linked in this PR template doesn't mention the cookbook at all, so maybe the README is just stale? Or does it mean the crate has to be both in the cookbook *and* in the top 100? (The wording really doesn't seem like it to me, but I could be wrong)

Sorry if I'm filing an issue pointlessly (and probably an annoying sort of issue you get a lot), feel free to close if this is the case!

**Comment by shepmaster** [comment]
> crates in the cookbook are present, but rusqlite is not present

The process for inclusion is pretty manual; we just have a big [list of crates](https://github.com/integer32llc/rust-playground/blob/5189288f6d67c2d5c11e6153f81a034d058ceefd/top-crates/crate-modifications.toml#L38-L79). My guess is that rusqlite was added after that list was generated.

The tough part will be to figure out what *other* crates are needed. It was always my hope that the cookbook would have a "simple" machine-readable file of all the crates that they use that we could just import every so often.

I suppose that the next step would be to get that list. Is that something you'd be interested in helping with? If not, I can just open an issue on their repository and start the ball rolling.

> the policy linked in this PR template doesn't mention the cookbook at all, so maybe the README is just stale

Or the linked policy isn't complete. It would probably make more sense somewhere else, such as either all in the README or a wiki page, or something.

It's certainly the *intent* that things from the cookbook are included.

> filing an issue pointlessly (and probably an annoying sort of issue you get a lot)

Not at all! Regardless of what happens with rusqlite specifically, there's some amount of drift between the two projects. You read things before asking, which already earns a big ❤️ from me.

**Comment by thomcc** [comment]
> I suppose that the next step would be to get that list. Is that something you'd be interested in helping with? If not, I can just open an issue on their repository and start the ball rolling.

I don't mind getting you the list (it's rather easy to pull out with some very hacky JS in the console as so, see end of comment), but I'm not particularly interested in coming up with a system for the rust-cookbook to distribute the list of crates they're using to avoid this happening in the future (I think that's a good idea -- probably a better one than just updating the list -- but it sounds a bit involved and I'm rather busy with work unfortunately).

---

Terrible code JS to pull the dependency list from the cookbook page:

```js
> Array.from(new Set(Array.from(document.querySelectorAll("table tbody tr td:first-child + td img[alt$=badge]"), i => i.parentNode.href)))
```

And then some cleanup to un-url things, remove the stdlib, etc. gives

```
[
    "rand",
    "clap",
    "ansi_term",
    "flate2",
    "tar",
    "crossbeam",
    "lazy_static",
    "threadpool",
    "walkdir",
    "num_cpus",
    "ring",
    "num",
    "image",
    "rayon",
    "glob",
    "data-encoding",
    "bitflags",
    "rusqlite",
    "postgres",
    "chrono",
    "log",
    "env_logger",
    "syslog",
    "log4rs",
    "semver",
    "cc",
    "url",
    "base64",
    "csv",
    "serde",
    "serde_json",
    "toml",
    "byteorder",
    "same-file",
    "memmap",
    "regex",
    "ndarray",
    "nalgebra",
    "unicode-segmentation",
    "reqwest",
    "select",
    "mime",
    "tempdir"
]
```

**Comment by shepmaster** [comment]
Looks like the diff is

```diff
+    "ansi_term",
     "base64",
     "bitflags",
     "byteorder",
+    "cc",
     "chrono",
     "clap",
     "crossbeam",
     "csv",
     "data-encoding",
     "env_logger",
-    "error-chain",
     "flate2",
-    "gcc",
     "glob",
     "image",
     "lazy_static",
     "log",
+    "log4rs",
     "memmap",
-    "mio",
+    "mime",
+    "nalgebra",
+    "ndarray",
     "num",
     "num_cpus",
-    "petgraph",
+    "postgres",
     "rand",
     "rayon",
     "regex",
     "reqwest",
     "ring",
+    "rusqlite",
+    "same-file",
     "select",
+    "semver",
     "serde",
-    "serde_derive",
     "serde_json",
     "syslog",
     "tar",
     "tempdir",
     "threadpool",
     "toml",
+    "unicode-segmentation",
     "url",
     "walkdir",
```
