### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by cbreeden** [integer32llc/rust-playground#52]
I administered a poll of 1 with 100% consensus (excluding me), so therefore have confirmed that it might be worth making the fontsize 14pt instead of 12pt in the editor.  Here are the differences for me:

![screenshot_20160822_155852](https://cloud.githubusercontent.com/assets/12069845/17871574/c292d03a-6881-11e6-8cbb-d6be9c6b31f3.png)

![screenshot_20160822_155944](https://cloud.githubusercontent.com/assets/12069845/17871578/c82f4410-6881-11e6-8c72-97000cf9b959.png)

I might just be getting old though.

**Comment by shepmaster** [comment]
> I administered a poll of 1 with 100% consensus (excluding me)

Thank you for your thorough research, but all true statistics should include error margins.

**Comment by shepmaster** [comment]
Have any objections to the overall font size increasing, not just for the editor? Out of curiosity, how do you feel the design of the site works when increasing the font size via the browser?

My only concern is the buttons in the top, as I'm afraid that there will just be more and more of them, and they already roll off the side at certain resolutions. A larger text size will exacerbate the problem.

**Comment by cbreeden** [comment]
So I took a look at my font settings for my browser (FF 48), and found that the default font size is set to 16pt.  This reason I brought this issue up was due to the inconsistency of font sizes with the buttons, output, and editor.  Here are various screenshots:

Default (Editor has 12pt font.)
![screenshot_20160822_161932](https://cloud.githubusercontent.com/assets/12069845/17872621/7e470f72-6886-11e6-991c-17fe02c1bab8.png)

Change `.ace_editor { font: ... }` to 14pt:
![screenshot_20160822_161947](https://cloud.githubusercontent.com/assets/12069845/17872645
/9bc11e9e-6886-11e6-88c9-eb557357cddf.png)

Change `.ace_editor { font: ... }` to 16pts (my default font size):
![screenshot_20160822_163357](https://cloud.githubusercontent.com/assets/12069845/17872657/aa7535e2-6886-11e6-84ba-94dbf325f7b1.png)

Increasing the font-size with the browser makes the problem more noticable.  Decreasing the font size to 12pts makes the fonts difficult to read, but then scaling the view port of the browser makes it easier to handle.

**Comment by cbreeden** [comment]
For got to answer one more:

>Have any objections to the overall font size increasing, not just for the editor?

No objections really.  Do you think it's possible to have the `ace_editor` font size match the default font size of the browser however?

**Comment by cbreeden** [comment]
So, I did a little more research.  The playground from rust-lang.org looks fine to me.  They also seem to have the same font declaration of some 12pt monospaced font as integer32 does.  But FF derives the font size differently somehow, and I don't know how.  These are the computed values for `<textarea>` from each site:

Rust-lang
![screenshot_20160822_165536](https://cloud.githubusercontent.com/assets/12069845/17873169/958a2234-6889-11e6-970a-957cc25ca01d.png)

Integer32
![screenshot_20160822_165426](https://cloud.githubusercontent.com/assets/12069845/17873189/a82aa242-6889-11e6-8d02-15524fe70360.png)

**Comment by shepmaster** [comment]
Respecting the user's font size is definitely something I'm in favor of, and I tend to use ems or percentages and eschew fixed font sizes. I didn't realize that the ACE editor themes had hard-coded point sizes!

> The playground from rust-lang.org looks fine to me

I think it makes sense that the header buttons be a bit bigger than the editor text and the output text. What would you say to using 90% of the base size for those two areas? The buttons would then be at 100% (16pt for you), then the body would be at 14.4 pt, very close to the 14.667 pt of the official playground. The editor text will become larger and the output text will get smaller, but they will match each other.

**Comment by shepmaster** [comment]
Also, this is intriguing: [browsers use a different font size for monospace fonts](http://code.stephenmorley.org/html-and-css/fixing-browsers-broken-monospace-font-handling/)... who knew!

**Comment by shepmaster** [comment]
Also, I'm going to remove the explicit font families from the editor, allowing the user's browser to set the monospace / serif / sans-serif. That way we can all have our favorite programmer font.

**Comment by cbreeden** [comment]
> What would you say to using 90% of the base size for those two areas?  

>  I'm going to remove the explicit font families from the editor, allowing the user's browser to set the monospace / serif / sans-serif.

Sounds good.  At least worth trying to see how it goes.

That link you posted is enlightening.  I just tested removing the `font` attribute and replacing it with `font-family: monospace` in the editor and FF is computing this to be 13px for me.  Weird, I never knew that browsers would do such a thing.

**Comment by shepmaster** [comment]
> Sounds good. At least worth trying to see how it goes.

Pushed live via #53; let me know how it seems.

**Comment by cbreeden** [comment]
I liked it.  Though, I did end up changing my default mono-spaced font.  I asked a bunch of people in #rust-offtopic and the responses were:

1 person - I don't like it.  And changing default fonts on a browser is lame. (Safari user)
Lots of people - It's a font! or Why are you asking me if I can change it anyway? (I guess indifferent?)

I don't know, maybe it's better to just provide a good default, since it's probably far from obvious that changing your default monospaced will yield better results for the random wanderer.

**Comment by shepmaster** [comment]
> maybe it's better to just provide a good default, since it's probably far from obvious that changing your default monospaced will yield better results for the random wanderer.

That's certainly possible. And it's nice because then I can just pick my own favorite font! Source Code Pro for everyone!

**Comment by shepmaster** [comment]
Ok, I'm going to close this in the hopes that it's better now! Let me know if I need to reopen.

Closed via #53 and #56.
