### ISSUE TITLE
Cursor jumps to beginning of file after typing character

### ISSUE THREAD

**Issue by joshtriplett** [integer32llc/rust-playground#527]
Typing a character in the editor, or pressing backspace in the editor, makes that change but then moves the cursor to the beginning of the file.

I can reproduce this in a new private browsing window. @Mark-Simulacrum could reproduce this too.

**Comment by shepmaster** [comment]
Hacky workaround for right now: switch to the simple editor: 

<img width="352" alt="image" src="https://user-images.githubusercontent.com/174509/63188615-d5888280-c02f-11e9-9565-416fbf6441b0.png">

**Comment by shepmaster** [comment]
The fix should be merged, then rolled out to production in the next 1-2 hours. After that, caching might bite you for the next 24h, so do a full reload of the page if you continue to see it. If you still see it after that, please reopen.
