### ISSUE TITLE
rand is unusable due to crate incompatibilities

### ISSUE THREAD

**Issue by orlp** [integer32llc/rust-playground#531]
The current rand crates included in the playground are:

```
rand = "=0.7.0"
rand_chacha = "=0.2.1"
rand_core = "=0.5.0"
rand_hc = "=0.2.0"
rand_isaac = "=0.1.1"
rand_jitter = "=0.1.4"
rand_os = "=0.1.3"
rand_pcg = "=0.1.2"
rand_xorshift = "=0.1.1"
```

I haven't checked all of them, but this makes the Pcg and XorShift RNGs unusable because they are outdated, and they are using an older version of `rand_core`. E.g.:

```
use rand_core::SeedableRng;
use rand_pcg::Pcg32;
fn main() {
    let _r = Pcg32::seed_from_u64(42);
}
```

This complains:

```
error[E0599]: no function or associated item named `seed_from_u64` found for type `rand_pcg::pcg64::Lcg64Xsh32` in the current scope
 --> src/main.rs:4:21
  |
4 |     let _r = Pcg32::seed_from_u64(42);
  |                     ^^^^^^^^^^^^^ function or associated item not found in `rand_pcg::pcg64::Lcg64Xsh32`
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
  |
1 | use rand_core::SeedableRng;
  |

warning: unused import: `rand_core::SeedableRng`
 --> src/main.rs:1:5
  |
1 | use rand_core::SeedableRng;
  |     ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

Due to incompatible crate versions.

**Comment by shepmaster** [comment]
You are correct, but I don't know much what to do here.

1. We get the [top downloaded crates and things from the cookbook](https://github.com/integer32llc/rust-playground/blob/fe8b1aa45bdbdc13aaf8bf0c46b4192f4ef0990b/top-crates/src/main.rs#L292-L293) 
1. We get the [newest versions from crates.io](https://github.com/integer32llc/rust-playground/blob/fe8b1aa45bdbdc13aaf8bf0c46b4192f4ef0990b/top-crates/src/main.rs#L298-L325)
1. We ask Cargo to [resolve the dependencies](https://github.com/integer32llc/rust-playground/blob/fe8b1aa45bdbdc13aaf8bf0c46b4192f4ef0990b/top-crates/src/main.rs#L332-L333)
1. We take the [latest version of each resolved crate](https://github.com/integer32llc/rust-playground/blob/fe8b1aa45bdbdc13aaf8bf0c46b4192f4ef0990b/top-crates/src/main.rs#L178-L189)

rand_{pcg,xorshift} is not one of the top-crates or a cookbook item, so it only shows up because it's a dependency. rand 0.7 does not depend on rand_{pcg,xorshift}, only rand 0.6.5 does:

```
[[package]]
name = "rand"
version = "0.6.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "autocfg 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.62 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_chacha 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_core 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_hc 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_isaac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_jitter 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_os 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_pcg 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_xorshift 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi 0.3.8 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "rand"
version = "0.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "getrandom 0.1.11 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.62 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_chacha 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_core 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand_hc 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

Thus the version of rand_{pcg,xorshift} that is included is the one that's compatible with the crate that needs it.

**Comment by shepmaster** [comment]
The only thing I can think of is that newer Cargo versions allow renaming. Instead of keeping only the unique crates, we could rename the older versions (and maybe *also* rename the newer ones for consistency?).

Something like:

```toml
rand = { version = "=0.7.0" }
rand_0_7_0 = { version = "=0.7.0", package = "rand" }
rand_0_6_5 = { version = "=0.6.5", package = "rand" }
```

Then you'd at least be able to do something along the lines of

```rust
use rand_core_0_6_5::SeedableRng;
use rand_pcg::Pcg32;
fn main() {
    let _r = Pcg32::seed_from_u64(42);
}
```

**Comment by shepmaster** [comment]
I'd be open to a pull request adding such a capability. We'd also have to make sure that the JSON file for the frontend data can handle that.

**Comment by orlp** [comment]
I don't think that'd be the right solution. Reading the code, hand-curating of certain crates already happens with `crate-modifications.toml`. Considering that `rand` is a cookbook crate as well, I think the best solution would be the hardcode some exception to also get the latest versions of the accompanying crates.

**Comment by shepmaster** [comment]
OK, in that case you will need to either

1. file an issue with the cookbook. We simply include their list of crates, so you will need to add the various rand_* crates to the cookbook and then we can include them here.

1. file an issue with rand. They can specify [metadata for extra features that they think should be enabled on the playground](https://github.com/integer32llc/rust-playground/issues/192#issuecomment-388589736)

The **playground** tries really hard to make no decisions about what crates to include. I simply don't want to get into the game of "why didn't you select *my* crate".

**Comment by orlp** [comment]
@shepmaster Could this be resolved by cargo features on `rand`? I don't see how.

**Comment by shepmaster** [comment]
> cargo features on `rand`? I don't see how.

It already [optionally depends on rand_pcg](https://github.com/rust-random/rand/blob/c388cb2d109e99afc3a48e0bbf90d15085e86156/Cargo.toml#L56-L58), so follow that pattern and add [all of the other generators](https://github.com/rust-random/rand/blob/c388cb2d109e99afc3a48e0bbf90d15085e86156/Cargo.toml#L42-L54) as optional dependencies, then create a feature that enables them and enable that feature for the playground.

**Comment by shepmaster** [comment]
The playground now supports importing all the crates we've compiled (#540) so this modified version works:

```
use rand_core_0_4_2::SeedableRng;
use rand_pcg::Pcg32;

fn main() {
    let _r = Pcg32::seed_from_u64(42);
}
```

Everything else appears to require upstream work, so I'm going to close this for now. Thanks!
