### ISSUE TITLE
Don't create public gists by default

### ISSUE THREAD

**Issue by AndrewRadev** [integer32llc/rust-playground#542]
Right now, when clicking "Share", it seems a public gist is created with the code. The problem with this is that code is immediately shared publicly rather than asking *how* it would be shared, and there's no way to undo it.

The specific situation goes like this: I'm the organizer of a Rust course and I've given a homework assignment. One student wrote a solution in the playground and wanted to send it to themselves via email, so they could work on it when they went back home. So they clicked "Share" and were surprised to see a public gist being created, which is not deletable now, because it's in the "rust-play" account. It's now possible to search for the module of the homework assignment to find the solution. Obviously, we'll be checking for plagiarism in general, but ideally, we'd like to avoid publicly visible homework solutions.

Maybe a simple way to fix this would be to create a private gist instead. It would still be shareable via URL, but it wouldn't show up in searches. Having a better share dialog with options and confirmations might be better in the long term, so maybe a "Share As..." button with options for a public or private gist.

**Comment by rw** [comment]
I love the Rust playground! But only today did I realize that ALL the code I was sharing with others through permalinks is actually added to the public list on rust-play's Gists. It's not explained anywhere on the UI, and it seems like a **scary default**. **Can we please bump this issue?**

**Comment by Stargateur** [comment]
how do you expect this would work if link were private ?!?

**Comment by shepmaster** [comment]
I don't mind this change, so if someone wants to cook up the appropriate PR, that would be wonderful.

**Comment by rw** [comment]
I tried making this configuration change: https://github.com/integer32llc/rust-playground/pull/570

**Comment by AndrewRadev** [comment]
Thanks!
