### ISSUE TITLE
Assembly output not working

### ISSUE THREAD

**Issue by luser** [integer32llc/rust-playground#546]
Something seems to be broken with assembly output. I get this:
```
   Compiling playground v0.0.1 (/playground)
warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type

warning: ignoring --out-dir flag due to -o flag

    Finished release [optimized] target(s) in 0.35s
```

I tried poking around the source but it was *just* complicated enough that I couldn't figure out how it was invoking rustc.

**Comment by shepmaster** [comment]
Works fine:

![image](https://user-images.githubusercontent.com/174509/69075234-f978ad00-09fe-11ea-93a6-d9df3b7a6ee3.png)

When reporting bugs, please consider providing steps to reproduce them.

**Comment by luser** [comment]
Sorry, this was a terrible bug report, I apologize! It turns out that the problem was that I didn't have a `main` function defined so presumably the compiler just optimized all my code away?

Here's the code I was using that was confusing me:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0f71298048ce3bfb1cf579450f57a934

Changing `fn foo` to `fn main` makes it produce actual output (which makes sense in hindsight):
https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=d5aef485ff6d3c2b3a9444771bc9ae2c

**Comment by shepmaster** [comment]
> I didn't have a `main` function defined so presumably the compiler just optimized all my code away?

Yes, or make it `pub fn foo`.
