### ISSUE TITLE
Miri is outdated

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#548]
The Miri on playground is from 2019-11-08, there have been quite a few updates since then.

**Comment by RalfJung** [comment]
@Aaron1011 see the build log at https://travis-ci.com/integer32llc/rust-playground/jobs/259856086:
```
error: failed to run custom build command for `html5ever v0.23.0`

Caused by:

  process didn't exit successfully: `/playground/target/debug/build/html5ever-e09cbe0abacfb0e8/build-script-build` (signal: 4, SIGILL: illegal instruction)
```
This might have to do with the `cfg(miri)` in libunwind?

**Comment by RalfJung** [comment]
This should be fixed by https://github.com/rust-lang/rust/pull/66822

**Comment by RalfJung** [comment]
@shepmaster This time [the Miri job ran successfully](https://travis-ci.com/integer32llc/rust-playground/jobs/263733189), but on playground it still says "2019-11-08". Any idea why?

**Comment by shepmaster** [comment]
Looking now, it says 12-04; perhaps just the timing between when it’s built and when the playground downloaded it?

**Comment by RalfJung** [comment]
Yeah must have been something like that.
