### ISSUE TITLE
Mapping :w to Ctrl+Enter

### ISSUE THREAD

**Issue by cbreeden** [integer32llc/rust-playground#55]
It was brought to my attention that many vim-mode users expect that `:w` compiles the code.

**Comment by shepmaster** [comment]
Interesting! I'm definitely an Emacs kind of person, but isn't `:w` the command to "write"? If so, how did that get mapped to "compile"? Is this something that is enabled in the official Playground?

**Comment by cbreeden** [comment]
Oh good question.  I just checked rust-lang and `:w` will compile the code.  This might be where they were all getting this expectation from.  I wasn't aware that that rust-lang had a vim mode to be honest :blush:

**Comment by durka** [comment]
I came here to ask for this and can confirm that the only reason I expected it to work is because the official playground does so.
