### ISSUE TITLE
Variable accessible after mutable borrow on playground

### ISSUE THREAD

**Issue by msaqib** [integer32llc/rust-playground#550]
Hi
I believe that [in this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=587a215428ca4c4b6ba1004c0bb0e5f1), line 11 should issue an error. But it isn't. 
Is this a bug?
Thanks
Saqib

**Comment by shepmaster** [comment]
This issue tracker is for the implementation of the Playground itself, not for questions / issues about the Rust language or crates.

That said, it isn't a bug. Reading [What are non-lexical lifetimes?](https://stackoverflow.com/q/50251487/155423) may help explain.
