### ISSUE TITLE
async/await is not highlighted in editor

### ISSUE THREAD

**Issue by lzutao** [integer32llc/rust-playground#555]
![image](https://user-images.githubusercontent.com/15225902/71147430-5fa15b80-225b-11ea-88e8-bc722ee90c99.png)

**Comment by shepmaster** [comment]
This is something that is provided by the Ace editor. You can contribute by submitting a pull request adding the appropriate highlighting to [rust_highlight_rules.js](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/rust_highlight_rules.js).

---

This is the Rust Playground, not the Playpen. It hasn't been called "Playpen" for many years.

**Comment by lzutao** [comment]
Opened https://github.com/ajaxorg/ace/pull/4137 .

> This is the Rust Playground, not the Playpen. It hasn't been called "Playpen" for many years.

TIL. Thank you. I used the word "playpen" because some official members of Rust in Reddit
and Discord called that too.

**Comment by shepmaster** [comment]
> I used the word "playpen" because some official members of Rust in Reddit
> and Discord called that too.

Yup, and I try to discourage that usage whenever I see it too 😄

**Comment by lzutao** [comment]
What should I do next after ajaxorg/ace#4137 ?

**Comment by shepmaster** [comment]
Now we wait for a release of Ace containing the fix. When it's available, we upgrade.

**Comment by lzutao** [comment]
New Ace release come: https://github.com/ajaxorg/ace-builds/releases/tag/v1.4.8
