### ISSUE TITLE
Nightly is outdated

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#560]
"Nightly" on https://play.rust-lang.org/ currently is from 2019-12-29, so a few days outdated. Looks like something is going wrong with the nightly updates.

(Also it seems impossible to copy-paste the version number from playground, which makes reporting such bugs more annoying that it would have to be...)

**Comment by RalfJung** [comment]
[From the CI logs](https://travis-ci.com/integer32llc/rust-playground/jobs/271727336), this looks like a build failure in matrixmultiply-0.2.3:
```
error: array lengths can't depend on generic parameters
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/sgemm_kernel.rs:223:40
    |
223 |     let mut ab = [_mm256_setzero_ps(); MR];
    |                                        ^^
```
Cc https://github.com/bluss/matrixmultiply/issues/50

**Comment by shepmaster** [comment]
> Also it seems impossible to copy-paste the version number from playground,

That’s a web browser limitation, as the text is inside a button. You’ll see I’ve added CSS to enable this but it only works in Chrome, IIRC.

**Comment by shepmaster** [comment]
Actually I might not have added that CSS. I’ll see if I can easily.

**Comment by shepmaster** [comment]
And the direct upstream issue is rust-lang/rust#67743

**Comment by RalfJung** [comment]
rustc is fixed, and nightly is updating again :)
