### ISSUE TITLE
Add button to delete/remove gist

### ISSUE THREAD

**Issue by joaoeudes7** [integer32llc/rust-playground#571]
The option to remove the shared gist would be interesting

**Comment by shepmaster** [comment]
This seems completely infeasible. There's no way to tell *who* created the gist originally (beyond the shared playground user), so this would mean that anyone could delete anyone else's shared code.

We recently stopped creating public gists (#542) and there's a non-prioritized un-tracked issue about creating gists under your own user, where you'd then have the ability to do what you need.

**Comment by joaoeudes7** [comment]
Great, that solves the problems
