### ISSUE TITLE
Any playground using the `rusqlite` crate fails to link to sqlite

### ISSUE THREAD

**Issue by thomcc** [integer32llc/rust-playground#580]
Example playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4f49430e77a4d398d126f6fc50e35c43 (Note that rusqlite is included in the playground as it was in the cookbook).

This should be fixable by turning on rusqlite's `bundled` feature which will make rusqlite build a static copy.

That said, I looked and am unsure where I could add that in a PR.

**Comment by shepmaster** [comment]
> That said, I looked and am unsure where I could add that in a PR.

To rusqlite itself, ideally:

https://github.com/integer32llc/rust-playground/issues/192#issuecomment-388589736

**Comment by thomcc** [comment]
Perfect, thanks.

**Comment by thomcc** [comment]
Ah, there's no way for us to know this actually fixes it prior to cutting a release (and possibly waiting for y'all to do an update? not sure if that's a step too), is there?

Like, could I build the playground locally, or am I just asking for trouble.

**Comment by thomcc** [comment]
Found the docs for this, will probably give it a stab but either way this can be closed, thanks!

**Comment by shepmaster** [comment]
> Like, could I build the playground locally

Yep, certainly! Let me know if it’s not obvious how to do this.
