### ISSUE TITLE
Could we add serde-transcode to the playground's crates?

### ISSUE THREAD

**Issue by rw** [integer32llc/rust-playground#581]
[serde-transcode](https://crates.io/crates/serde-transcode) is a utility crate that is important enough to be explained in the [toplevel of serde's documentation](https://serde.rs/transcode.html).

However, it's not popular enough on its own to be included in the top-N crates on the playground.

Could we it add manually? Thanks!

**Comment by shepmaster** [comment]
https://github.com/integer32llc/rust-playground/blob/master/CRATE_POLICY.md
