### ISSUE TITLE
Access to Ace editor instace from global namesapce

### ISSUE THREAD

**Issue by ear7h** [integer32llc/rust-playground#592]
I'm not sure if this is already the case but it would be nice to be able to access the editor instance from the global namespace (ex. `window.ace`, something more hacky is okay too if the editor instance being kept as an attribute of a dom element) in order to add a makeshift `.vimrc` file via [tampermonkey](https://www.tampermonkey.net/).

An example of this behavior is currently in the overleaf latex editor, [here's their guide](https://www.overleaf.com/learn/how-to/How_can_I_define_custom_Vim_macros_in_a_vimrc_file_on_Overleaf%3F#Example_script_with_TamperMonkey_to_add_keybindings).

**Comment by nightwing** [comment]
you can use `document.querySelector(".ace_editor").env.editor`, may need a more specific selector if there are multiple editors on the page

**Comment by ear7h** [comment]
@nightwing thank you!

If anyone comes across this here's my full user script

```js
// ==UserScript==
// @name         play.rust-lang.org vimrc
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://play.rust-lang.org/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    // poll until editor is loaded
    const retry = setInterval(() => {
        // get current editor instance
        let editor = document.querySelector(".ace_editor").env.editor

        if (editor === undefined) return
        clearInterval(retry)

        // vim keyboard plugin
        const vimKeyboard = window.ace.require("ace/keyboard/vim")
        // add custom keybindings - insert mode applies on insert
        vimKeyboard.Vim.map("jj", "<Esc>", "insert")
        // normal mode applies while escaped
        vimKeyboard.Vim.map("<C-k>", "<C-u>", "normal")
        vimKeyboard.Vim.map("<C-j>", "<C-d>", "normal")
        // set the modified keyboard handler for editor
        editor.setKeyboardHandler(vimKeyboard.handler)
        console.log("Custom key bindings applied")
    }, 100)
})();
```
