### ISSUE TITLE
demo compile error

### ISSUE THREAD

**Issue by zzz6519003** [integer32llc/rust-playground#593]
Compiling playground v0.0.1 (/playground)
error[E0594]: cannot assign to data in an `Arc`
  --> src/main.rs:22:13
   |
22 |             status_shared.jobs_completed += 1;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot assign
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `std::sync::Arc<JobStatus>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0594`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

**Comment by shepmaster** [comment]
It’s unclear why you have opened an issue. You haven’t provided any code, and the error to show seems correct. Perhaps you are having issues getting started with Rust? If so perhaps start with reading [The Rust Programming Language](https://doc.rust-lang.org/book/).

**Comment by zzz6519003** [comment]
default code

**Comment by shepmaster** [comment]
The [default code is](https://github.com/integer32llc/rust-playground/blob/77ce403cd0d4d2da0d4d424e841ce30623e3a209/ui/frontend/reducers/code.ts#L3-L5):

```
fn main() {
    println!("Hello, world!");
}
```

Perhaps you followed a link from another web site that populated the code.

**Comment by zzz6519003** [comment]
nintendo！
