### ISSUE TITLE
expired HTTPS certificate

### ISSUE THREAD

**Issue by TomPridham** [integer32llc/rust-playground#594]
it seems like the letsencrypt https cert isn't set to auto renew and has expired

![Screenshot from 2020-04-14 10-34-09](https://user-images.githubusercontent.com/8271228/79250171-8a7f7300-7e3b-11ea-97e3-ec607ebd66dd.png)

**Comment by shepmaster** [comment]
![image](https://user-images.githubusercontent.com/174509/79254856-5c0d9200-7e53-11ea-9ac7-3040b6b7b008.png)

**Comment by shepmaster** [comment]
AFAICT, the problem was that I must have uninstalled the `certbot` tool inadvertently. I was notified about this on 2020-02-16, but forgot to deal with the email then!
