### ISSUE TITLE
Suggestion: Add a reset button

### ISSUE THREAD

**Issue by Wilfred** [integer32llc/rust-playground#598]
Preserving the state in the Rust playground is often helpful. Sometimes, I want a fresh hello world program I can edit though.

Would it be possible to add a reset button? I think this would be particularly useful for newcomers, who are unfamiliar with basic Rust syntax.

I can't see any way of doing this today, except opening the playground in an incognito browser.

**Comment by Wilfred** [comment]
This would probably help with #595.

**Comment by shepmaster** [comment]
Duplicate of #323
