### ISSUE TITLE
"const fn main" not detected as main function.

### ISSUE THREAD

**Issue by bluss** [integer32llc/rust-playground#613]
Feature request: detect "const fn main" as a main function. 😈

The following program says it doesn't detect a main function:

```rust
const fn main() -> Result<(), ()> {
    Err(())
}
```

But if you ~~fool it~~ use the playground-approved indenting standard:

```rust
const
fn main() -> Result<(), ()> {
    Err(())
}
```

it runs!

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/playground`
Error: ()
```

**Comment by shepmaster** [comment]
> it runs!

_what_

**Comment by shepmaster** [comment]
As another hack, you can force it to run via the dropdown:

![image](https://user-images.githubusercontent.com/174509/86173777-81bf4480-baee-11ea-861d-80c184e434b3.png)
