### ISSUE TITLE
Vim keybindings: `cG` does not delete file when run on the first line

### ISSUE THREAD

**Issue by jyn514** [integer32llc/rust-playground#649]
`dG` works correctly: delete the whole file, starting from the current line.
However, `cG` is buggy and actually doesn't delete anything at all, it just inserts a new line above.

When run on any line other than the very first, it works fine.

**Comment by shepmaster** [comment]
Can you try it on [the kitchen sink](https://ace.c9.io/build/kitchen-sink.html)? If it fails there, then it's an upstream issue.

**Comment by jyn514** [comment]
Yes, it also fails there. Should I report this on https://github.com/ajaxorg/ace?

**Comment by shepmaster** [comment]
Yes, please. Feel free to cross-link.

**Comment by shepmaster** [comment]
I'll actually keep this open to check every so often for an Ace update.

**Comment by bobrippling** [comment]
@shepmaster my PR to fix this has been merged - we can close this issue once you're happy to bring in the upstream.

**Comment by shepmaster** [comment]
I don't believe a new version of Ace has been released, so waiting for that.

**Comment by jyn514** [comment]
This works now :)
