### ISSUE TITLE
Remove the "open a rust-lang/rust issue" link

### ISSUE THREAD

**Issue by jonas-schievink** [integer32llc/rust-playground#671]
The "Open an issue on the Rust GitHub repository" link on the Share window is frequently used to open spam issues that we then have to close manually. Since opening an issue manually just involves copying code and output by hand, I am not sure it is pulling its weight. Perhaps it would be better to remove it?

**Comment by shepmaster** [comment]
Can you link me to some of the spam issues?

**Comment by jonas-schievink** [comment]
The recent ones were:
https://github.com/rust-lang/rust/issues/81009
https://github.com/rust-lang/rust/issues/81010
https://github.com/rust-lang/rust/issues/81014
https://github.com/rust-lang/rust/issues/81016
https://github.com/rust-lang/rust/issues/81019
https://github.com/rust-lang/rust/issues/81020

Some older ones:
https://github.com/rust-lang/rust/issues/80773
https://github.com/rust-lang/rust/issues/76125
https://github.com/rust-lang/rust/issues/72418
https://github.com/rust-lang/rust/issues/67275
https://github.com/rust-lang/rust/issues/66992
https://github.com/rust-lang/rust/issues/65814
https://github.com/rust-lang/rust/issues/58076

**Comment by jonas-schievink** [comment]
Some more spam issues caused by this:
https://github.com/rust-lang/rust/issues/83617
https://github.com/rust-lang/rust/issues/83620

**Comment by camelid** [comment]
I understand that this was used to create spam issues, but I have found this feature very useful and use it a lot. The primary way I use it is to quickly be able to copy

- code,
- playground link, and
- output

all at once. I find it tedious to do it manually. Is there some kind of replacement feature that could be added where it would let me copy what used to go into the GitHub issue body? E.g., it would output this to a textbox that could be copied:

`````markdown
Code ([playground](...)):

```rust
...
```

Output:

```
...
```
`````

I would find that very useful.

**Comment by shepmaster** [comment]
There's a few possibilities, sure. Off the top of my head:

1. We could remove the `<a>` tag and only have the copy icon. That way you'd have to deliberately paste it into your address bar, but otherwise it'd be the same as what previously existed.
2. Use a collapsed/expandable textbox like you mentioned.

@jonas-schievink do you have any intuition about why GitHub issues were comparatively spammed? I've not heard anyone complain about the same misuse on the user's forum, for example.

**Comment by jonas-schievink** [comment]
I've seen one URLO spam post that clearly came from the playground: https://users.rust-lang.org/t/marvinrivera1234/58204

I'm not aware of others, but I'm not too active on URLO. I suspect GitHub gets more spam because more people have an account there (and it keeps you logged in permanently).

I'd be fine with outputting copy-pastable markdown for the forum and GitHub, that shouldn't cause any spam issues as long as you omit the link. Having a non-clickable, but copyable link might still cause spam, so I'd rather avoid that.

**Comment by camelid** [comment]
Yeah, the copy-pastable textbox would actually work even better than the GitHub issue link for me because I often copy-paste from the issue body into Zulip or an issue or PR comment instead of opening the issue.

**Comment by camelid** [comment]
I opened an issue: #708
