### ISSUE TITLE
Make Window Resizable

### ISSUE THREAD

**Issue by TNkemdilim** [integer32llc/rust-playground#673]
I really like ability to switch the playgrounds orientation to either `vertical` or `horizontal`. A step further will be to make provision for resizing both panels.

I sometimes find myself having to minimize/maximize the terminal panel to have more code space.

E.g. 
- Small screen: I might want the `code section` to be a lot wider while the `terminal section` a lot smaller (vertical orientation)
- Large screen: I could leave it on the default.

This is just an improvement to #162.

If this feature is deemed fit, I could work on a PR for it.

**Comment by shepmaster** [comment]
Duplicate of #302

**Comment by shepmaster** [comment]
This is certainly a desired feature!
