### ISSUE TITLE
Add support for --edition=2021 on nightly

### ISSUE THREAD

**Issue by m-ou-se** [integer32llc/rust-playground#678]
The nightly compiler now have support for `--edition=2021` with `-Zunstable-options`. It might be nice to have an option for that on the playground.

**Comment by kangalioo** [comment]
Said option exists now, so I think this issue can be closed?
![Screenshot_20210929_162953](https://user-images.githubusercontent.com/21220820/135289404-750186b6-eeeb-46d7-af8d-2a94bc9aa2a5.png)

**Comment by shepmaster** [comment]
Closed by #717
