### ISSUE TITLE
Please add/update [smol]

### ISSUE THREAD

**Issue by keepsimple1** [integer32llc/rust-playground#682]
Please read [our crate policy][policy]. Any issue opened for a new or updated crate version will be closed with a reference to the same policy.

[policy]: https://github.com/integer32llc/rust-playground/blob/master/CRATE_POLICY.md

Hi,

Any possibility to add async runtime support in addition to `tokio`?  For example, `smol` ? 

Thank you!

**Comment by shepmaster** [comment]
# Please read [our crate policy][policy]. Any issue opened for a new or updated crate version will be closed with a reference to the same policy.

[policy]: https://github.com/integer32llc/rust-playground/blob/master/CRATE_POLICY.md
