### ISSUE TITLE
Using Miri first builds some crates

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#684]
It looks like somehow Miri doesn't come with fully pre-built crates any more on the playground: when I open [this code](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=2b703739165302d627d369a84785909c) and run it in Miri, it starts doing this in the output:
```
   Compiling hyper v0.14.4
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.0
```
Most of the time, it then timeouts, probably because building the dependencies takes too long.

We have done some changes to cargo-miri in the recent past that fixed in particular the interaction with hyper (https://github.com/rust-lang/miri/issues/1705), so maybe the cache needs to be cleared and re-built somehow? But I thought that was supposed to happen automatically.

**Comment by shepmaster** [comment]
CI [appears to be precompiling those crates](https://github.com/integer32llc/rust-playground/runs/1984488474?check_suite_focus=true) (click on "build and push container"):

```
#8 146.2    Compiling hyper v0.14.4
551
#8 146.7    Compiling cookie_store v0.12.0
552
#8 147.2    Compiling select v0.5.0
553
#8 147.5    Compiling postgres v0.19.0
554
#8 149.7    Compiling hyper-tls v0.5.0
555
#8 149.9    Compiling reqwest v0.11.0
556
#8 151.1    Compiling playground v0.0.1 (/playground)
557
#8 151.1     Finished dev [unoptimized + debuginfo] target(s) in 2m 30s
558
#8 151.1      Running `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri target/x86_64-unknown-linux-gnu/debug/playground`
559
#8 151.2 Hello, world!
```

**Comment by RalfJung** [comment]
> Is this still the right setup to do before running the user code?

Yeah, I would think so. However, it's possible that old files sticking around could confuse cargo-miri... does this process start with an empty `target` directory each time, or does it reuse the one from the previous day?

**Comment by shepmaster** [comment]
The intention (and everything I've seen previously) is that it's a completely clean build.

**Comment by RalfJung** [comment]
Yeah this is a Miri bug: https://github.com/rust-lang/miri/issues/1722

**Comment by RalfJung** [comment]
Closing this then, bors is testing the fix for Miri now and eventually it should make its way through to the playground.

**Comment by shepmaster** [comment]
Thank you!
