### ISSUE TITLE
Suggest using nightly on E0658

### ISSUE THREAD

**Issue by jyn514** [integer32llc/rust-playground#694]
[E0658](https://doc.rust-lang.org/error-index.html#E0658) is "An unstable feature was used." Playground [already suggests](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f19ce045905d77bc015c3493238826c7) adding `#![feature(...)]` on nightly channels; it would be nice for it to suggest switching to nightly too.

**Comment by jyn514** [comment]
Same for https://doc.rust-lang.org/stable/error-index.html#E0554 (not sure what the difference between the two is).

**Comment by shepmaster** [comment]
Duplicate of #314
