### ISSUE TITLE
Include crates recommended as part of the compiler output

### ISSUE THREAD

**Issue by upsuper** [integer32llc/rust-playground#718]
If you grep `https://crates.io/crates/` in `*.stderr` files in Rust compiler's source code, you will find there are two crates currently mentioned: [async-trait](https://crates.io/crates/async-trait) and [async-recursion](https://crates.io/crates/async_recursion), which are useful crates to workaround some of annoying restrictions Rust currently has.

async-trait has already been included, and I think it would be good to include async-recursion as well, so that people can try out it when the compiler asks them to.

**Comment by shepmaster** [comment]
You used an issue template, but instead of [reading it](https://github.com/integer32llc/rust-playground/blob/master/CRATE_POLICY.md), you deleted it and ignored it. Please re-read it.
