### ISSUE TITLE
Please add/update tracing-subscriber

### ISSUE THREAD

**Issue by insanitybit** [integer32llc/rust-playground#725]
tracing and tracing-core are already provided, but to my knowledge these crates aren't really useful without a subscriber. For that reason I think that tracing-subscriber should be added, even if it maybe doesn't strictly fall under the policy.

If not, I understand - thanks for this great service either way!

**Comment by shepmaster** [comment]
You used an issue template, but instead of [reading it](https://github.com/integer32llc/rust-playground/blob/master/CRATE_POLICY.md), you deleted it and ignored it. Please re-read it.

**Comment by shepmaster** [comment]
> I think that tracing-subscriber should be added

If you want to see this happen, then I suggest you contribute content to the [cookbook](https://rust-lang-nursery.github.io/rust-cookbook/), showing how to use tracing-subscriber. Once you've done that, it will be pulled in automatically.
