### ISSUE TITLE
Prevent frequent timeouts

### ISSUE THREAD

**Issue by kangalioo** [integer32llc/rust-playground#762]
Unfortunately, the playground often times out during compilation, presumably due to high load. Usually it takes quite a while until any code can be run again.

To fix this, the timeout duration could be increased from 10 seconds to a higher value.

Alternatively, `cargo build` and `cargo run` could have different timeouts, for example 15 seconds for compilation and 2 seconds for running.

**Comment by shepmaster** [comment]
Duplicate of #712
