### ISSUE TITLE
Setting to ignore dead code/unused warnings

### ISSUE THREAD

**Issue by rmccampbell** [integer32llc/rust-playground#774]
I find it is vary rarely useful to have unused variable and dead code warnings for the Playground. Often I just declare some functions and variables to see if something compiles as I expect, and having superfluous warnings crowding the console makes it less obvious whether the compilation actually succeeded. Of course I can add `#![allow(unused_variables/dead_code)]`  at the top but that's extra boilerplate I have to add each time. If it was a setting it could set it at the compiler level and be remembered across sessions.

**Comment by shepmaster** [comment]
Thanks for the suggestion, but I don't agree with it and don't plan on implementing it.

I prefer that the playground align as close to "regular" Rust / Cargo as possible and not create its own dialect. As you mentioned, you can add the `allow` inner attribute; you can also mark things as `pub` when building a library (without a `main`).
