### ISSUE TITLE
"Expand macros" produces incorrect code when variable is shadowed?

### ISSUE THREAD

**Issue by nirvana-msu** [integer32llc/rust-playground#811]
I was trying to see what happens if I try to use a variable in a macro with same name as in the outer scope, and I think I stumbled upon a bug somewhere.

Let's say I have [this macro](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7d034bb75c715e3804971909a7c91525), which internally uses a variable with same name `val` as in the outer scope:
```
macro_rules! assign_if_ne {
    ($lhs:expr, $value:expr) => ({
        let val = $value;
        if $lhs != val {
            $lhs = val;
        }
    })
}

struct Test {
    x: u8,
}
fn main() {
    let mut val = Test { x: 5 };
    assign_if_ne!(val.x, 2+7);
    println!("{}", val.x)
}
```

To my delight, Rust is smart enough to not conflate the uses of different `val` variables and the code prints `9` as a result. However if I try to use "Expand macros" feature of the playground, it shows me this code:
```
let mut val = Test { x: 5 };
{ let val = 2 + 7; if val.x != val { val.x = val; } };
```
This is not a valid Rust code and it doesn't even compile. Clearly rust macro is doing something smarter than this - it somehow realises that `val.x` still refers to `val` from the outer scope, despite `val` being shadowed within the macro scope.

**Comment by nirvana-msu** [comment]
Ok, I should have read [cargo-expand disclaimer](https://github.com/dtolnay/cargo-expand/#disclaimer) first - it is apparently expected.

**Comment by shepmaster** [comment]
Yep. Pedantically, we don't use `cargo-expand`, but the problem arises from the compiler so both avenues have the same issue.
