### ISSUE TITLE
Please add hex

### ISSUE THREAD

**Issue by gilescope** [integer32llc/rust-playground#830]
[policy]: https://github.com/integer32llc/rust-playground/blob/master/CRATE_POLICY.md

policy says use data_encoding crate but hex crate has 4x the downloads and people can remember what it's called.
Not convinced that people easily can decode hex using the existing crate:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ae1aa28c55afa9f0ea0e7aa0ed8bd1a8

Adding hex would make playing with rust a bit easier in my opinion, feel free to close this if you don't agree.

**Comment by shepmaster** [comment]
If you wish to change what the [Rust Cookbook](https://rust-lang-nursery.github.io/rust-cookbook/) suggests, the appropriate thing to do is to open a PR over there.

Neither the hex crate nor the data-encoding crate are in the top 100 most downloaded crates, nor are they a transitive dependency of them.

**Comment by gilescope** [comment]
None of the top 100 crates has a transative dependency that decodes hex?
That seems really quiet unlikely…

**Comment by shepmaster** [comment]
Please feel free to double check my work — if it's wrong, then there's a bug in the dependency resolver we use and I'd want to fix it.

**Comment by Deleplace** [comment]
Adding `hex` would be nice for people like me who are learning Rust and are eager to test the hex functions they just learned. Also, Programming-Idioms [considers](https://programming-idioms.org/search/hexadecimal+digits+rust) `hex` idiomatic (the contributions might be right or wrong about this). 

I learned about "data_encoding" here for the first time today, thank you for the relevant Cookbook section link!

**Comment by shepmaster** [comment]
> Adding `hex` would be nice

If you wish to change what the [Rust Cookbook](https://rust-lang-nursery.github.io/rust-cookbook/) suggests, the appropriate thing to do is to open a PR over there.

**Comment by Deleplace** [comment]
I do not wish to change the Rust Cookbook.

@shepmaster I could not find the list of the top 100 most downloaded crates made available in the playground. Do you have a link, or is it something I should generate myself by running a command, in order to at least know what I can use?

**Comment by shepmaster** [comment]
> I could not find the list of the top 100 most downloaded crates

https://play.rust-lang.org/help#features-crates

![image](https://user-images.githubusercontent.com/174509/211342139-40306721-1801-4c30-b693-3255a7b75a99.png)

https://github.com/integer32llc/rust-playground/blob/master/compiler/base/Cargo.toml

**Comment by Deleplace** [comment]
Thanks @shepmaster
