### ISSUE TITLE
Miri on the playground is outdated

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#836]
The playground has a Miri from 2022-08-13. That is [not the latest version](https://rust-lang.github.io/rustup-components-history/).

**Comment by RalfJung** [comment]
Looks like for some time now, all job s in the [scheduled rebuild](https://github.com/integer32llc/rust-playground/actions/runs/2900966090) have failed -- not just the Miri job.

**Comment by RalfJung** [comment]
The underlying error seems to be
```
error: failed to select a version for the requirement `bytemuck = "=1.12.0"`
```
That version was [yanked](https://crates.io/crates/bytemuck/versions), which is probably the cause of the problem.

Cc @Lokathor

**Comment by Lokathor** [comment]
Sorry about that yank. There was an accidental problem with how repr(align(N)) was being treated by the proc-macros and it was breaking builds. The `1.12.1` fixes things, if you can do an update to that.

**Comment by Lokathor** [comment]
https://github.com/integer32llc/rust-playground/commit/e91313f889d36ac2ba32256efea57a163d5cf649 should let things build again

**Comment by RalfJung** [comment]
Yes, there's newer Miri on the playground now. :)
