### ISSUE TITLE
Playground zooming way too much on mobile version of Chrome

### ISSUE THREAD

**Issue by RpxdYTX** [integer32llc/rust-playground#846]
For some reason, the playground started dooing microscopic zooms when clicking on any part of it, it is very annoying. I used it some months ago to test some snippets, and some time ago it became that annoying.

**Comment by shepmaster** [comment]
In general, the fancy editors don't support mobile. Try switching to a native textbox instead:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/174509/191013964-946bfa05-64e2-40c1-becb-41db2b9bb661.png">

**Comment by RpxdYTX** [comment]
Simple does work without zooming to the pixels of a letter, but even though i don't mind losing syntax highlighting, things like auto indentation and closing brackets (+ everything else) are very convenient.
I'll be using simple as a workaround, but could an editor not be as fancy as ace but work fine with those utilities like the one that that [Programiz](https://programiz.com/c-programming/online-compiler) website uses? I mean, if it was done, it can be done again.

**Comment by shepmaster** [comment]
> like the one that that [Programiz](https://programiz.com/c-programming/online-compiler) website uses

Interesting, as it appears that site even uses Ace!

```html
<div id="editor" class=" ace_editor ace_hidpi ace-tm">
```

I've opened #847 to check into that.
