### ISSUE TITLE
Ubuntu 22.04 Firefox hangs when I press ctrl-s on the Rust Playground

### ISSUE THREAD

**Issue by eric-seppanen** [integer32llc/rust-playground#848]
I discovered today that pressing ctrl-s on the Rust Playground causes Firefox to hang: the file dialog opens but is flickering and unresponsive.

If I go into about:config and set `permissions.default.shortcuts = 2` (disabling sites' ability to override keyboard shortcuts) then ctrl-s does the (relatively useless) browser default thing (save the whole page).

I'm not sure if this is a site bug or an Ubuntu or Firefox bug; feel free to close this if it's not the site.

I have a fairly plain install of Ubuntu 22.04 with the default configuration (snap package) Firefox 105.0-2.

**Comment by eric-seppanen** [comment]
I am also able to toggle between hanging/not-hanging by going into Tools->Page Info, then Permissions->Override Keyboard Shortcuts set to Block.

**Comment by eric-seppanen** [comment]
I was able to reproduce this on the sample Ace editor on https://ace.c9.io/ . I'll report this there instead.

**Comment by shepmaster** [comment]
ajaxorg/ace#4932
