### ISSUE TITLE
Support library crates, including ASM and LLVM IR

### ISSUE THREAD

**Issue by bluss** [integer32llc/rust-playground#85]
This is how I'd use the official playground to look at asm or llvm ir for a single function:

[play.integer32 link](http://play.integer32.com/?gist=144275c86b6b0059da26eecbaa79ba8c&version=nightly)

[play.rust-lang link](https://play.rust-lang.org/?gist=144275c86b6b0059da26eecbaa79ba8c)

```rust
#![crate_type="lib"]

pub fn memory(b: Box<[u8]>) {
    
}
```

on this playground, I can't find the way to do what I wanted (the single pub function emitted as asm/llvm ir by itself).

**Comment by shepmaster** [comment]
Compared to the official playground, I use Cargo for everything — have to, that's how crates are accessible. The code you type is always written to `src/main.rs`, thus why the error occurs.

**Comment by shepmaster** [comment]
It also appears that the nightly branch suffers a timeout of some kind when trying to produce LLVM IR / assembly...

**Comment by shepmaster** [comment]
Do you have any suggestions how to change from a binary crate to a library crate? I'm afraid that it would involve some amount of detection (is there a `main` function, maybe?) and then writing to `src/lib.rs` instead of `src/main.rs`?

**Comment by bluss** [comment]
Thanks for putting this issue in context for me, I didn't think anything about how the playpen here was implemented before filing.

Potentially detect libraries just from `#![crate_type="lib"]` ? Since that's something that works in the other one. Without that context, it's a pretty strange user interface, sure. The original playpen also has an "fn main" detector to toggle between Run as binary and Run as `--test` compiled binary. If we dwell on this I think a better playpen doesn't use those solutions, but something more explicit?

I was wondering, is there any way the asm/llvm ir buttons work as it is now? A program like this doesn't generate any output for them either:

```rust
fn main() { }
```

**Comment by shepmaster** [comment]
> I was wondering, is there any way the asm/llvm ir buttons work as it is now? A program like this doesn't generate any output for them either:

Are you still using the nightly channel? Looks like they moved the location of the generated file - which I've opened #86 for.

**Comment by bluss** [comment]
Oh, that was the issue.

**Comment by shepmaster** [comment]
> Potentially detect libraries just from #![crate_type="lib"] ? Since that's something that works in the other one. 

Since I do want to maintain compatibility with the official playground, this is probably how we can start. 

> Without that context, it's a pretty strange user interface, sure.

Yeah; a backlog item I have (#46) is to add some kind of help page to at least make some of the magic discoverable.

> The original playpen also has an "fn main" detector to toggle between Run as binary and Run as --test compiled binary. 

I stole that idea too 😇 

> If we dwell on this I think a better playpen doesn't use those solutions, but something more explicit?

I've thought about having something like a dropdown that allows explicitly choosing a way to run the code. Cower in the face of my amazing mockup skills:

![image](https://cloud.githubusercontent.com/assets/174509/21035694/de17d956-bd8e-11e6-952b-def61907e7a3.png)

**Comment by shepmaster** [comment]
Although closed, this needs a small update to the underlying docker containers; it will probably be really available a few hours after midnight UTC.

**Comment by shepmaster** [comment]
> probably be really available a few hours after midnight UTC.

Nope, I broke the containers. Probably tomorrow 😇

**Comment by shepmaster** [comment]
@bluss OK, please give it a shot now; the containers are updated.

**Comment by bluss** [comment]
it works!
