### ISSUE TITLE
[frontend] retain Orientation vertical / horizontal in UI

### ISSUE THREAD

**Issue by jiangying000** [integer32llc/rust-playground#853]
Maybe add a option to enable frontend retain Orientation vertical / horizontal settting in UI if user changed it manually ?

**Comment by shepmaster** [comment]
We already have that

![CE43E1C2-9FF6-425D-996F-F46286D92204](https://user-images.githubusercontent.com/174509/193410203-0ae8f90a-9223-4469-b550-bace6fa37562.jpeg)

you will need to clarify what you mean otherwise

**Comment by jiangying000** [comment]
I remember when I changed the `UI -> orientation` option to `Vertical` manually, it was reverted to `Automatic` after some time, maybe several days later.

I am not very sure about this behavior can be reproduced, will keep watching this

**Comment by jiangying000** [comment]
unable to reproduce, thanks
