### ISSUE TITLE
Please enable the `macros` feature for the `phf` crate

### ISSUE THREAD

**Issue by ChaiTRex** [integer32llc/rust-playground#877]
I can't use `use phf::phf_map;`, which is a very common way of using that crate, because the `macros` feature of the `phf` crate is not selected. As the docs for that macro say:

> [Requires the `macros` feature.](https://docs.rs/phf/latest/phf/macro.phf_map.html)

**Comment by shepmaster** [comment]
Ask the PHF maintainers to [enable playground metadata](https://github.com/integer32llc/rust-playground/issues/192#issuecomment-388589736)

**Comment by ChaiTRex** [comment]
Requested in rust-phf/rust-phf#275.
