### ISSUE TITLE
[Request] Security Policy

### ISSUE THREAD

**Issue by LeoDog896** [integer32llc/rust-playground#878]
For any security vulnerabilities that may leave the main server vulnerable, you may want a way to encourage ethical security researchers to safely disclose it. [GitHub has a guide](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) on setting up one of these, for assistance.

Just some preferred contact method(s) for reporting vulnerabilities would be great.

**Comment by shepmaster** [comment]
Good call, thanks!
