### ISSUE TITLE
Terminal emulation with xterm

### ISSUE THREAD

**Issue by LeoDog896** [integer32llc/rust-playground#879]
Emulate color codes (for any CLI-style crates):

[xterm.js](http://xtermjs.org/) makes this very simple, and is used by projects such as [genact](https://github.com/svenstaro/genact) ([demo page with xterm](https://svenstaro.github.io/genact/)).

**Comment by shepmaster** [comment]
This is an implementation detail. #900 does a better job of explaining the request.
