### ISSUE TITLE
Playground now deletes `gist` query parameter

### ISSUE THREAD

**Issue by ChaiTRex** [integer32llc/rust-playground#884]
Suddenly, the playground both at https://play.rust-lang.org and https://play.integer32.com redirect a URL with a `gist` query parameter to a URL without that parameter, which makes it more difficult to shorten the URL and then test that the shortened URL works, because the shortened URL is destroyed in the process.

**Comment by shepmaster** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/174509/213776629-49f72e08-a2b3-4d83-abad-44450a188d4b.png">

Please take care to use the appropriate issue template (or lack of template)

**Comment by shepmaster** [comment]
This is likely an aftershock from [some changes I made recently](https://github.com/integer32llc/rust-playground/commit/652943de2fbde45933a7f0057d321d0f2ae1862e). Luckily, #873 should fix this **and** make things better.

**Comment by WaffleLapkin** [comment]
#873 is merged and appears to have fixed this, should we close this issue?
