### ISSUE TITLE
I have to scroll too much

### ISSUE THREAD

**Issue by carols10cents** [integer32llc/rust-playground#9]
## What happened 

I ran some code that I was interested to see either the output or the compilation errors for. After I clicked Run, I had to scroll to see most of the output that I was interested in.

## What I expected to happen

On the official playground, I can see a lot more of the output without having to scroll. I am le tired.

Example on this playground:

<img width="1280" alt="screen shot 2016-06-29 at 7 16 41 pm" src="https://cloud.githubusercontent.com/assets/193874/16473837/5ac467a2-3e2e-11e6-8d42-72f4783469ca.png">

Example on the official playground:

<img width="1280" alt="screen shot 2016-06-29 at 7 17 00 pm" src="https://cloud.githubusercontent.com/assets/193874/16473842/60f7d870-3e2e-11e6-8cdb-ab1135fd88ec.png">

**Comment by shepmaster** [comment]
Could you check out the latest update and see if it improves the scrolling situation?

**Comment by carols10cents** [comment]
It does indeed, thank you!!! It's gorgeous.

<img width="1275" alt="screen shot 2016-07-05 at 9 35 48 am" src="https://cloud.githubusercontent.com/assets/193874/16586445/f7faf842-4293-11e6-994f-00f0a42f4f32.png">
